"""Grid Lens Integration."""
from __future__ import annotations

import logging

from homeassistant.components import persistent_notification
from homeassistant.config_entries import ConfigEntry
from homeassistant.const import Platform
from homeassistant.core import HomeAssistant
import aiohttp
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator
from homeassistant.helpers.aiohttp_client import async_get_clientsession

from .const import DOMAIN, PLAN_ID_TO_KEY, CONF_DISTRIBUTOR, CONF_DEFERRABLE_LOAD_SENSORS

_LOGGER = logging.getLogger(__name__)

PLATFORMS: list[Platform] = [Platform.SENSOR, Platform.SWITCH, Platform.NUMBER, Platform.SELECT]

_HISTORY_STORAGE_KEY = "grid_lens_plan_history"
_HISTORY_STORAGE_VERSION = 1

_DIAGNOSTIC_README = """\
Grid Lens — Diagnostic Export
================================================
Generated by the Home Assistant 'grid_lens' integration.
Share this file when reporting a bug. No credentials or API keys are included —
only entity IDs and energy statistics.

Contents:
  README.txt                — This file
  info.json                 — HA version, calculation period, configured sensor entity IDs
  config.json               — Battery and deferrable load configuration
  plan_rates.json           — All plan rate structures used in the calculation
  calculation_summary.json  — Per-plan costs and savings vs current plan
  energy_flows.json         — Hourly energy flows (first 24 hours of period)
  plans/<plan>.json         — Per-plan LP schedules, bill breakdowns, hourly profiles
"""


def _build_seed_views(hass: HomeAssistant) -> list[dict]:
    """Dashboard views seeded for a brand-new install.

    Every entity id is resolved from the entity registry by the unique_id each
    platform assigns (f"{entry.entry_id}_..."), never hardcoded — a config entry's
    device-name-derived slug (e.g. "roof_grid_lens_nsw") is unique per install and
    can't be guessed. Cards/tiles that need an entity which doesn't resolve (no
    battery configured, no deferrable loads, etc.) are simply omitted rather than
    shipping a broken reference. See CLAUDE.md's "build for the general case, not
    this install" — nothing here should assume a specific inverter brand or account.
    """
    from homeassistant.helpers import entity_registry as er

    entries = hass.config_entries.async_entries(DOMAIN)
    if not entries:
        # Shouldn't happen (this only runs once a config entry exists), but with
        # no entry to resolve real entity ids against, fall back to a bare card.
        return [{
            "type": "panel", "title": "Plan Comparison", "path": "plan-comparison",
            "cards": [{"type": "custom:grid-lens-card"}],
        }]
    # One shared "Grid Lens" dashboard, so a multi-entry install just gets the
    # first entry's data — matches how the dashboard itself is domain-wide today.
    entry = entries[0]
    reg = er.async_get(hass)

    def eid(unique_id: str) -> str | None:
        for domain in ("sensor", "switch", "number"):
            found = reg.async_get_entity_id(domain, DOMAIN, unique_id)
            if found:
                return found
        return None

    current_plan_cost = eid(f"{entry.entry_id}_current_plan_cost")
    plan_comparison_view = {
        "type": "panel", "title": "Plan Comparison", "path": "plan-comparison",
        "cards": [{
            "type": "custom:grid-lens-card",
            **({"entity": current_plan_cost} if current_plan_cost else {}),
        }],
    }
    views = [plan_comparison_view]

    dispatch = eid(f"{entry.entry_id}_planned_dispatch")
    if not dispatch:
        # Advisory/battery-plan system not set up for this entry (e.g. still
        # initializing) — the Plan Comparison view alone is still useful.
        return views

    top_row = [{
        "type": "custom:grid-lens-flex-row-card",
        "gap": 16,
        "cards": [
            {
                "type": "custom:grid-lens-powerflow-card",
                # height/width/flex must move together — the diagram is square, so a
                # size bump here (e.g. to fit a taller node label) that doesn't keep
                # all three in lockstep distorts the aspect ratio instead.
                "max_height": 700, "max_width": 700, "flex": "0 1 700px",
                "icon_scale": 1.5, "font_scale": 0.7,
                # Live solar/grid/battery/EV POWER sensors aren't collected by
                # config_flow (only daily-energy sensors are, for the plan-
                # comparison LP) — the card falls back to its own built-in example
                # defaults until that's added as a proper config field. SOC is
                # genuinely install-agnostic config already, so pass it through.
                **({"soc_entity": entry.data.get("battery_soc_sensor")}
                   if entry.data.get("battery_soc_sensor") else {}),
            },
            {
                "type": "custom:grid-lens-power-chart-card",
                "entity": dispatch, "max_height": 615, "flex": "1 1 300px",
            },
        ],
        "grid_options": {"columns": "full"},
    }]

    # Tunable settings (numeric overrides) and control switches both go on the
    # separate "Settings" view below, not "Battery Plan" — keeps the operational/
    # monitoring view free of things you set once and forget, per user request
    # 2026-07-29 ("move the configuration stuff into a new page").
    # Min export price lives NEXT TO the battery-control switch in the Control section
    # (not under Tuning) — user request 2026-07-30: it's the knob most often touched
    # alongside that switch, so they sit together at the top of Settings.
    control_tiles = []
    if entry.data.get("has_battery"):
        min_export = eid(f"{entry.entry_id}_min_export_price")
        if min_export:
            control_tiles.append({
                "type": "tile", "entity": min_export, "name": "Min export price",
                "features": [{"type": "numeric-input"}],
            })
    # Today Boost tiles used to live here as their own "Tuning" section — merged into
    # grid-lens-load-control-card's per-device rows 2026-07-31 (user request: "move the
    # boost control into this same settings area"), so nothing further is seeded for it.
    deferrable_sensors = entry.data.get(CONF_DEFERRABLE_LOAD_SENSORS, []) or []

    battery_control = eid(f"{entry.entry_id}_battery_control")

    status_tiles = []
    for label, key in (
        ("Now", "advisory_next_action"), ("SOC now", "advisory_soc_now"),
        ("Planned end", "advisory_planned_end_soc"), ("Plan net cost", "advisory_net_cost"),
    ):
        found = eid(f"{entry.entry_id}_{key}")
        if found:
            status_tiles.append({"type": "tile", "entity": found, "name": label})

    sections = [{"column_span": 3, "cards": top_row}]
    if status_tiles:
        sections.append({"column_span": 3, "cards": [{
            "type": "grid", "columns": len(status_tiles), "square": False,
            "cards": status_tiles, "grid_options": {"columns": "full"},
        }]})
    sections.append({"column_span": 3, "cards": [{
        "type": "custom:grid-lens-advisory-card", "entity": dispatch,
        "grid_options": {"columns": "full"},
    }]})
    for card_kind in ("soc", "dispatch", "price", "cash"):
        sections.append({"column_span": 3, "cards": [{
            "type": f"custom:grid-lens-{card_kind}-chart-card", "entity": dispatch,
            "grid_options": {"columns": "full"},
        }]})

    views.append({
        "path": "plan", "type": "sections", "icon": "mdi:battery-clock",
        "title": "Battery Plan", "max_columns": 3, "dense_section_placement": False,
        "header": {"layout": "responsive", "badges_position": "bottom", "badges_wrap": "wrap"},
        "cards": [], "sections": sections,
    })

    # Settings view: control switches (battery + deferrable loads — the load-control
    # card is genuinely dynamic, so it's included whenever any deferrable load is
    # configured, whether or not a control switch has been assigned to one yet; its
    # own empty state points the user at Reconfigure) plus tunable numeric overrides.
    # Only added at all if there's something to put on it.
    settings_cards = []
    if battery_control:
        settings_cards.append({
            "type": "heading", "heading": "Control", "heading_style": "title",
            "icon": "mdi:toggle-switch-outline", "grid_options": {"columns": "full"},
        })
        settings_cards.append({
            "type": "grid", "columns": 2, "square": False,
            "cards": [
                # A real tile dict (the previous seed put the bare entity-id string in
                # `cards`, which Lovelace doesn't accept — latent, since existing
                # installs are never re-seeded), matching this install's live layout.
                {
                    "type": "tile", "entity": battery_control, "name": "Battery control",
                    "state_content": ["state", "note"], "features": [{"type": "toggle"}],
                },
                *control_tiles,
            ],
            "grid_options": {"columns": "full"},
        })
    if deferrable_sensors:
        if not battery_control:
            settings_cards.append({
                "type": "heading", "heading": "Control", "heading_style": "title",
                "icon": "mdi:toggle-switch-outline", "grid_options": {"columns": "full"},
            })
        settings_cards.append({
            "type": "custom:grid-lens-load-control-card", "title": "Deferrable Loads",
            "grid_options": {"columns": "full"},
        })
        # Weekly gantt-style editor of when each deferrable load may run (per-weekday
        # allowed hours, painted on a 7x24 grid; saved via grid_lens.set_deferrable_schedule).
        settings_cards.append({
            "type": "heading", "heading": "Schedules", "heading_style": "title",
            "icon": "mdi:calendar-clock", "grid_options": {"columns": "full"},
        })
        settings_cards.append({
            "type": "custom:grid-lens-defer-schedule-card", "title": "Allowed Run Times",
            "grid_options": {"columns": "full"},
        })
    # "Add / reconfigure a device" link, at the BOTTOM (user request 2026-07-31 — a
    # top-of-page button read as too prominent). Structural config (which HA entities are
    # your solar/battery/deferrable-load sensors and switches, adding a new device) still
    # has to go through HA's config_flow/options_flow (it's what creates the config entry
    # data everything else here reads), which lives on a different screen (Settings >
    # Devices & Services) than this dashboard. Rather than trying to fold that
    # live-reactive-vs-form-submit mismatch into one screen (config_flow has no
    # instant-apply, which is exactly why min_export_price/overrides/boost/greedy were
    # deliberately moved OFF config_flow onto dashboard entities in the first place — see
    # the checklist), a one-click link keeps setup and tuning one click apart instead of
    # requiring the user to remember/hunt for the separate screen. `/config/integrations/
    # integration/{domain}` is a stable HA frontend route that filters straight to this
    # integration's entries, independent of entry_id/instance-specific naming. Appended
    # unconditionally (even with nothing else configured yet) so a fresh install still
    # gets a minimal Settings view pointing the user at where to go configure something.
    settings_cards.append({
        "type": "heading", "heading": "Setup", "heading_style": "title",
        "icon": "mdi:cog-outline", "grid_options": {"columns": "full"},
    })
    settings_cards.append({
        "type": "button", "name": "Reconfigure Grid Lens", "icon": "mdi:tune-variant",
        "show_state": False,
        "tap_action": {
            "action": "navigate",
            "navigation_path": "/config/integrations/integration/grid_lens",
        },
        "grid_options": {"columns": "full"},
    })
    if settings_cards:
        views.append({
            "path": "settings", "type": "sections", "icon": "mdi:cog",
            "title": "Settings", "max_columns": 2, "dense_section_placement": False,
            "header": {"layout": "responsive", "badges_position": "bottom", "badges_wrap": "wrap"},
            "cards": [], "sections": [{"column_span": 2, "cards": settings_cards}],
        })

    return views


def _plan_from_history(entries: list, start_date) -> str | None:
    """Return the plan name active at start_date (latest entry whose date <= start_date)."""
    query = start_date.date().isoformat() if hasattr(start_date, 'date') else str(start_date)[:10]
    active = None
    for entry in sorted(entries, key=lambda e: e['date']):
        if entry['date'] <= query:
            active = entry['plan_name']
    return active


async def async_setup(hass: HomeAssistant, config: dict) -> bool:
    """Set up the Grid Lens component."""
    import pathlib
    import uuid as _uuid
    from homeassistant.helpers.storage import Store
    from homeassistant.const import EVENT_HOMEASSISTANT_STARTED

    # Serve www/ directly from the integration directory
    www_path = str(pathlib.Path(__file__).parent / "www")
    try:
        from homeassistant.components.http import StaticPathConfig
        await hass.http.async_register_static_paths(
            [StaticPathConfig("/grid_lens", www_path, False)]
        )
    except Exception as e:
        _LOGGER.warning("Could not register static path for Grid Lens: %s", e)

    # Register Lovelace resource modules using the runtime collection (like simple_timer)
    # This ensures the frontend is notified immediately and stale entries are cleaned up.
    # Every card URL carries a ?v= cache-buster: HA's static-path caching for /grid_lens
    # is disabled (cache_headers=False above), but browsers still hold onto an
    # already-imported ES module for the tab's lifetime — bumping the query string
    # forces a genuinely new URL so a plain restart (without this) can silently
    # leave users on stale card JS even after a hard-refresh.
    _CARD_VERSION = "20260816a"
    card_urls = [
        f"/grid_lens/cards/grid-lens-card.js?v={_CARD_VERSION}",
        f"/grid_lens/cards/grid-lens-flow-card.js?v={_CARD_VERSION}",
        # Gated: served by PowerflowCardView (proxied from the API, entitlement-checked),
        # not HA's static /grid_lens/cards/ tree — see that view's docstring.
        f"/api/grid_lens/cards/grid-lens-powerflow-card.js?v={_CARD_VERSION}",
        f"/grid_lens/cards/grid-lens-advisory-card.js?v={_CARD_VERSION}",
        f"/grid_lens/cards/grid-lens-soc-chart-card.js?v={_CARD_VERSION}",
        f"/grid_lens/cards/grid-lens-dispatch-chart-card.js?v={_CARD_VERSION}",
        f"/grid_lens/cards/grid-lens-power-chart-card.js?v={_CARD_VERSION}",
        f"/grid_lens/cards/grid-lens-price-chart-card.js?v={_CARD_VERSION}",
        f"/grid_lens/cards/grid-lens-cash-chart-card.js?v={_CARD_VERSION}",
        f"/grid_lens/cards/grid-lens-flex-row-card.js?v={_CARD_VERSION}",
        f"/grid_lens/cards/grid-lens-load-control-card.js?v={_CARD_VERSION}",
        f"/grid_lens/cards/grid-lens-boost-tuning-card.js?v={_CARD_VERSION}",
        f"/grid_lens/cards/grid-lens-defer-schedule-card.js?v={_CARD_VERSION}",
    ]
    stale_urls = {
        "/grid_lens/cards/electricity-plan-comparison-card.js",
        "/grid_lens/cards/electricity-energy-flow-card.js",
        "/local/grid-lens/electricity-energy-flow-card.js",
        "/local/grid-lens/electricity-plan-comparison-card.js",
        # The Power Flow card moved from a static file to a gated proxy URL
        # (PowerflowCardView) 2026-08-02 — the base path itself changed, so the
        # version-mismatch check below won't catch it; needs the explicit stale entry.
        "/grid_lens/cards/grid-lens-powerflow-card.js",
    }
    try:
        lovelace_data = hass.data.get("lovelace")
        if lovelace_data and hasattr(lovelace_data, "resources"):
            resources = lovelace_data.resources
            await resources.async_get_info()
            # Remove legacy-named stale entries, plus any entry whose base URL
            # matches a current card but whose query string (version) is outdated.
            desired_by_base = {url.split("?")[0]: url for url in card_urls}
            for item in list(resources.async_items()):
                item_url = item.get("url", "")
                base = item_url.split("?")[0]
                if base in stale_urls or (base in desired_by_base and item_url != desired_by_base[base]):
                    try:
                        await resources.async_delete_item(item["id"])
                    except Exception:
                        pass
            # Add entries that aren't already present at their current version
            existing = {item.get("url", "") for item in resources.async_items()}
            for url in card_urls:
                if url not in existing:
                    await resources.async_create_item({"res_type": "module", "url": url})
        else:
            # Fallback: write directly to store
            resources_store = Store(hass, 1, "lovelace_resources")
            data = await resources_store.async_load() or {"items": []}
            desired_by_base = {url.split("?")[0]: url for url in card_urls}
            data["items"] = [
                i for i in data["items"]
                if i["url"].split("?")[0] not in stale_urls
                and not (i["url"].split("?")[0] in desired_by_base and i["url"] != desired_by_base[i["url"].split("?")[0]])
            ]
            existing_urls = {item["url"] for item in data["items"]}
            for url in card_urls:
                if url not in existing_urls:
                    data["items"].append({"id": str(_uuid.uuid4()), "type": "module", "url": url})
            await resources_store.async_save(data)
    except Exception as e:
        _LOGGER.warning("Could not register Lovelace resources for Grid Lens: %s", e)

    # Auto-register the Grid Lens dashboard in the sidebar
    async def _register_dashboard(_event=None):
        lovelace_data = hass.data.get("lovelace")
        if not lovelace_data or not hasattr(lovelace_data, "dashboards"):
            _LOGGER.warning("Grid Lens: lovelace not available, skipping dashboard registration")
            return
        try:
            dashboards = lovelace_data.dashboards

            dashboard_config = {
                "id": "grid_lens",
                "icon": "mdi:transmission-tower",
                "title": "Grid Lens",
                "url_path": "grid-lens",
                "require_admin": False,
                "mode": "storage",
                "show_in_sidebar": True,
            }

            # Persist to lovelace_dashboards store (read by HA on next startup)
            dash_store = Store(hass, 1, "lovelace_dashboards")
            dash_data = await dash_store.async_load() or {"items": []}
            already_stored = any(d.get("url_path") == "grid-lens" for d in dash_data.get("items", []))
            if not already_stored:
                dash_data.setdefault("items", []).append(dashboard_config)
                await dash_store.async_save(dash_data)

            # Seed dashboard content if not yet created
            content_store = Store(hass, 1, "lovelace.grid_lens")
            if not await content_store.async_load():
                await content_store.async_save({
                    "config": {
                        "title": "Grid Lens",
                        "views": _build_seed_views(hass),
                    }
                })

            # If already registered in-memory, nothing more to do
            if isinstance(dashboards, dict) and "grid-lens" in dashboards:
                return
            if not isinstance(dashboards, dict) and any(
                d.get("url_path") == "grid-lens" for d in dashboards.async_items()
            ):
                return

            # In HA 2026 dashboards is a plain dict; try adding the LovelaceStorage
            # object directly so the sidebar updates without a restart.
            if isinstance(dashboards, dict):
                try:
                    from homeassistant.components.lovelace.dashboard import LovelaceStorage as _LS
                    dashboards["grid-lens"] = _LS(hass, dashboard_config)
                    _LOGGER.info("Grid Lens dashboard added to sidebar")
                except Exception:
                    _LOGGER.info("Grid Lens dashboard written to storage — will appear in sidebar after next HA restart")
            else:
                await dashboards.async_create_item(dashboard_config)
                _LOGGER.info("Grid Lens dashboard registered in sidebar")
        except Exception as e:
            _LOGGER.warning("Could not register Grid Lens dashboard: %s", e)

    if hass.is_running:
        hass.async_create_task(_register_dashboard())
    else:
        hass.bus.async_listen_once(EVENT_HOMEASSISTANT_STARTED, _register_dashboard)

    from aiohttp import web
    from homeassistant.components.http import HomeAssistantView

    class PlanDataView(HomeAssistantView):
        """Serve plan optimization data for dashboard."""
        
        url = "/api/grid_lens/plan_data"
        name = "api:grid_lens:plan_data"
        requires_auth = False
        
        def __init__(self, hass_instance):
            self.hass = hass_instance
        
        async def get(self, request):
            """Get plan optimization data with optional date range."""
            import json
            from datetime import datetime

            # Parse dates in the HA configured timezone so "May 12 00:00" means
            # local midnight, not UTC midnight (which would be wrong for AEST).
            try:
                from zoneinfo import ZoneInfo
            except ImportError:
                from backports.zoneinfo import ZoneInfo
            ha_tz = ZoneInfo(self.hass.config.time_zone or "UTC")

            start_date_str = request.query.get('start_date')
            end_date_str = request.query.get('end_date')
            start_date = None
            end_date = None

            if start_date_str:
                try:
                    start_date = datetime.fromisoformat(
                        start_date_str.replace('Z', '+00:00')
                    )
                    if start_date.tzinfo is None:
                        start_date = start_date.replace(tzinfo=ha_tz)
                except ValueError:
                    return web.Response(
                        text=json.dumps({'error': 'Invalid start_date format'}),
                        content_type='application/json',
                        status=400
                    )

            if end_date_str:
                try:
                    end_date = datetime.fromisoformat(
                        end_date_str.replace('Z', '+00:00')
                    )
                    if end_date.tzinfo is None:
                        end_date = end_date.replace(tzinfo=ha_tz)
                except ValueError:
                    return web.Response(
                        text=json.dumps({'error': 'Invalid end_date format'}),
                        content_type='application/json',
                        status=400
                    )

            entries = self.hass.config_entries.async_entries(DOMAIN)
            if not entries:
                return web.Response(
                    text=json.dumps({'error': 'Integration not loaded'}),
                    content_type='application/json',
                    status=404
                )

            coordinator = self.hass.data.get(DOMAIN, {}).get(entries[0].entry_id)
            if not coordinator:
                return web.Response(
                    text=json.dumps({'error': 'No coordinator'}),
                    content_type='application/json',
                    status=404
                )

            # Custom date range: recalculate on-the-fly and return directly.
            if start_date or end_date:
                import aiohttp as _aiohttp
                from .plan_calculator import PlanCalculator
                from .const import CONF_GRIDLENS_API_KEY, CONF_GRIDLENS_API_URL, CONF_STATE
                from homeassistant.helpers.storage import Store
                entries = self.hass.config_entries.async_entries(DOMAIN)
                entry_obj = entries[0] if entries else None
                if not entry_obj:
                    return web.Response(text=json.dumps({'error': 'No entry'}), content_type='application/json', status=404)
                _api_key = entry_obj.data.get(CONF_GRIDLENS_API_KEY, "")
                _api_url = entry_obj.data.get(CONF_GRIDLENS_API_URL, "https://api.gridlens.au")
                _state   = entry_obj.data.get(CONF_STATE, "NSW")
                _network = entry_obj.data.get(CONF_DISTRIBUTOR, "")
                _plan_data: dict = {}
                _network_operators: dict = {}
                try:
                    _sess = async_get_clientsession(self.hass)
                    _current_plan = entry_obj.data.get("current_plan", "")
                    async with _sess.get(f"{_api_url}/plans",
                                         params={"state": _state, "current_plan": _current_plan, "network": _network},
                                         headers={"X-API-Key": _api_key, "User-Agent": "GridLens-HA-Integration/1.0"},
                                         timeout=_aiohttp.ClientTimeout(total=15)) as _r:
                        if _r.status == 200:
                            _resp_data = await _r.json()
                            _plan_data = _resp_data.get("plans", {})
                            _network_operators = _resp_data.get("network_operators", {})
                except Exception as _exc:
                    _LOGGER.warning("plan-rates: could not fetch plan data: %s", _exc)
                calculator = PlanCalculator(self.hass, entry_obj)
                calculator.plan_data = _plan_data
                calculator.network_operators = _network_operators

                # Derive which plan the user was actually on at start_date from change history.
                if start_date:
                    _hist_store = Store(self.hass, _HISTORY_STORAGE_VERSION, _HISTORY_STORAGE_KEY)
                    _hist_data = await _hist_store.async_load() or {"entries": []}
                    _hist_plan = _plan_from_history(_hist_data["entries"], start_date)
                    if _hist_plan:
                        calculator.current_plan_override = _hist_plan
                        _LOGGER.info("History: current plan at %s is %s", start_date.date(), _hist_plan)

                response_data = await calculator.calculate_plan_costs(start_date, end_date)
                _LOGGER.info(f"Custom date range calculation complete: {response_data.get('usage_days')} days")
                return web.Response(
                    text=json.dumps(response_data),
                    content_type='application/json'
                )

            # Default: use coordinator cached data (populated on startup).
            if not coordinator.data:
                return web.Response(
                    text=json.dumps({'status': 'calculating'}),
                    content_type='application/json',
                    status=202
                )

            plan_details = coordinator.data.get('plan_details', {})
            response_data = {
                'plan_details': plan_details,
                'energy_flows': coordinator.data.get('energy_flows', {}),
                'current_plan_total': coordinator.data.get('current_plan_total', 0),
                'current_plan_name': coordinator.data.get('current_plan_name'),
                'deferrable_devices': coordinator.data.get('deferrable_devices', []),
                'usage_days': coordinator.data.get('usage_days', 0),
                'start_date': coordinator.data.get('start_date', ''),
                'end_date': coordinator.data.get('end_date', ''),
                'calculation_date': coordinator.data.get('calculation_date', ''),
            }

            return web.Response(
                text=json.dumps(response_data),
                content_type='application/json'
            )
    
    class PlanHistoryView(HomeAssistantView):
        """List and create plan change history entries."""

        url = "/api/grid_lens/plan_history"
        name = "api:grid_lens:plan_history"
        requires_auth = False

        def __init__(self, hass_instance):
            self.hass = hass_instance

        async def get(self, request):
            import json
            from homeassistant.helpers.storage import Store
            store = Store(self.hass, _HISTORY_STORAGE_VERSION, _HISTORY_STORAGE_KEY)
            data = await store.async_load() or {"entries": []}
            return web.Response(text=json.dumps(data), content_type='application/json')

        async def post(self, request):
            import json, uuid
            from homeassistant.helpers.storage import Store
            try:
                body = await request.json()
            except Exception:
                return web.Response(text=json.dumps({'error': 'Invalid JSON'}),
                                    content_type='application/json', status=400)
            if not body.get('date') or not body.get('plan_name'):
                return web.Response(text=json.dumps({'error': 'date and plan_name required'}),
                                    content_type='application/json', status=400)
            store = Store(self.hass, _HISTORY_STORAGE_VERSION, _HISTORY_STORAGE_KEY)
            data = await store.async_load() or {"entries": []}
            entry = {
                "id": str(uuid.uuid4()),
                "date": body['date'],
                "plan_name": body['plan_name'],
                "notes": body.get('notes', ''),
            }
            data["entries"].append(entry)
            await store.async_save(data)
            return web.Response(text=json.dumps({"entry": entry}), content_type='application/json')

    class PlanHistoryItemView(HomeAssistantView):
        """Update and delete individual plan change history entries."""

        url = "/api/grid_lens/plan_history/{entry_id}"
        name = "api:grid_lens:plan_history_item"
        requires_auth = False

        def __init__(self, hass_instance):
            self.hass = hass_instance

        async def put(self, request, entry_id):
            import json
            from homeassistant.helpers.storage import Store
            try:
                body = await request.json()
            except Exception:
                return web.Response(text=json.dumps({'error': 'Invalid JSON'}),
                                    content_type='application/json', status=400)
            store = Store(self.hass, _HISTORY_STORAGE_VERSION, _HISTORY_STORAGE_KEY)
            data = await store.async_load() or {"entries": []}
            for i, entry in enumerate(data["entries"]):
                if entry["id"] == entry_id:
                    data["entries"][i] = {
                        "id": entry_id,
                        "date": body.get('date', entry['date']),
                        "plan_name": body.get('plan_name', entry['plan_name']),
                        "notes": body.get('notes', entry.get('notes', '')),
                    }
                    await store.async_save(data)
                    return web.Response(text=json.dumps({"entry": data["entries"][i]}),
                                        content_type='application/json')
            return web.Response(text=json.dumps({'error': 'Not found'}),
                                content_type='application/json', status=404)

        async def delete(self, request, entry_id):
            import json
            from homeassistant.helpers.storage import Store
            store = Store(self.hass, _HISTORY_STORAGE_VERSION, _HISTORY_STORAGE_KEY)
            data = await store.async_load() or {"entries": []}
            before = len(data["entries"])
            data["entries"] = [e for e in data["entries"] if e["id"] != entry_id]
            if len(data["entries"]) == before:
                return web.Response(text=json.dumps({'error': 'Not found'}),
                                    content_type='application/json', status=404)
            await store.async_save(data)
            return web.Response(text=json.dumps({"ok": True}), content_type='application/json')

    class DiagnosticExportView(HomeAssistantView):
        """Export all calculation inputs and outputs as a zip for bug reporting."""

        url = "/api/grid_lens/diagnostic_export"
        name = "api:grid_lens:diagnostic_export"
        requires_auth = False

        def __init__(self, hass_instance):
            self.hass = hass_instance

        async def get(self, request):
            import io, json, zipfile
            from datetime import datetime as _dt

            entries = self.hass.config_entries.async_entries(DOMAIN)
            coordinator = self.hass.data.get(DOMAIN, {}).get(entries[0].entry_id) if entries else None

            if not coordinator:
                return web.Response(
                    text=json.dumps({'error': 'Integration not loaded'}),
                    content_type='application/json',
                    status=404,
                )
            if not coordinator.data:
                return web.Response(
                    text=json.dumps({'status': 'no_data', 'message': 'No calculation yet. Load the dashboard first.'}),
                    content_type='application/json',
                    status=202,
                )

            data = coordinator.data
            entry = coordinator.entry

            try:
                from homeassistant.const import __version__ as ha_version
            except Exception:
                ha_version = 'unknown'

            buf = io.BytesIO()
            timestamp = _dt.now().strftime('%Y%m%d_%H%M%S')

            with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zf:
                zf.writestr('README.txt', _DIAGNOSTIC_README)

                # System info and sensor entity IDs
                info = {
                    'exported_at': _dt.now().isoformat(),
                    'ha_version': ha_version,
                    'integration_domain': DOMAIN,
                    'calculation_date': data.get('calculation_date', ''),
                    'period_start': data.get('start_date', ''),
                    'period_end': data.get('end_date', ''),
                    'usage_days': data.get('usage_days', 0),
                    'current_plan': data.get('current_plan_name', ''),
                    'sensors': {
                        'energy': entry.data.get('energy_sensor', ''),
                        'solar': entry.data.get('solar_sensor', ''),
                        'grid_export': entry.data.get('grid_export_sensor', ''),
                        'import_price': entry.data.get('import_price_sensor', ''),
                        'export_price': entry.data.get('export_price_sensor', ''),
                        'battery_soc': entry.data.get('battery_soc_sensor', ''),
                        'battery_power': entry.data.get('battery_charge_power_sensor', ''),
                    },
                }
                zf.writestr('info.json', json.dumps(info, indent=2, default=str))

                # Battery and deferrable load configuration
                config = {
                    'has_battery': entry.data.get('has_battery', False),
                    'battery_capacity_kwh': entry.data.get('battery_capacity', 13.5),
                    'battery_max_charge_kw': entry.data.get('battery_max_charge_rate', 5.0),
                    'battery_max_discharge_kw': entry.data.get('battery_max_discharge_rate', 5.0),
                    'battery_efficiency_pct': entry.data.get('battery_efficiency', 95.0),
                    'battery_min_soc_pct': entry.data.get('battery_min_soc', 10.0),
                    'battery_max_soc_pct': entry.data.get('battery_max_soc', 90.0),
                    'deferrable_load_sensors': entry.data.get('deferrable_load_sensors', []),
                    'deferrable_load_max_kw': entry.data.get('deferrable_load_max_kw', []),
                }
                zf.writestr('config.json', json.dumps(config, indent=2, default=str))

                # All plan rate structures (from cached coordinator data, if available)
                coordinator_data = self.hass.data.get(DOMAIN, {}).get(entry_obj.entry_id)
                if coordinator_data and hasattr(coordinator_data, 'data') and coordinator_data.data:
                    plan_rates = coordinator_data.data.get('plan_data', {})
                    zf.writestr('plan_rates.json', json.dumps(plan_rates, indent=2, default=str))

                # Per-plan costs and savings
                summary = {
                    'current_plan': data.get('current_plan_name'),
                    'current_plan_total_dollars': data.get('current_plan_total', 0),
                    'usage_days': data.get('usage_days', 0),
                    'period_start': data.get('start_date'),
                    'period_end': data.get('end_date'),
                    'plan_costs': data.get('alternative_plans', {}),
                    'savings_vs_current': {
                        k: v for k, v in data.items() if k.endswith('_vs_current')
                    },
                }
                zf.writestr('calculation_summary.json', json.dumps(summary, indent=2, default=str))

                # Energy flows (first 24h)
                zf.writestr('energy_flows.json', json.dumps(
                    data.get('energy_flows', {}), indent=2, default=str
                ))

                # Per-plan LP schedules, breakdowns, and hourly profiles
                for plan_key, detail in data.get('plan_details', {}).items():
                    safe_name = ''.join(
                        c if c.isalnum() or c in '-_' else '_' for c in plan_key
                    )
                    opt = detail.get('optimization') or {}
                    plan_export = {
                        'plan_key': plan_key,
                        'strategy': detail.get('strategy', ''),
                        'plan_info': detail.get('plan_info', {}),
                        'breakdown': detail.get('breakdown', {}),
                        'hourly_profile_24h': detail.get('hourly_profile', []),
                        'optimization_totals': {
                            k: v for k, v in opt.items()
                            if k not in ('schedule', 'day_profile')
                        },
                        'lp_schedule': opt.get('schedule', []),
                    }
                    zf.writestr(
                        f'plans/{safe_name}.json',
                        json.dumps(plan_export, indent=2, default=str),
                    )

            buf.seek(0)
            filename = f"epc_diagnostic_{timestamp}.zip"
            return web.Response(
                body=buf.read(),
                content_type='application/zip',
                headers={'Content-Disposition': f'attachment; filename="{filename}"'},
            )

    class PlanStreamView(HomeAssistantView):
        """Stream plan results one-by-one via Server-Sent Events as each LP finishes."""

        url = "/api/grid_lens/plan_stream"
        name = "api:grid_lens:plan_stream"
        requires_auth = False

        def __init__(self, hass_instance):
            self.hass = hass_instance

        async def get(self, request):
            import json
            from datetime import datetime
            try:
                from zoneinfo import ZoneInfo
            except ImportError:
                from backports.zoneinfo import ZoneInfo
            ha_tz = ZoneInfo(self.hass.config.time_zone or "UTC")

            def _parse_date(s):
                if not s:
                    return None
                dt = datetime.fromisoformat(s.replace('Z', '+00:00'))
                return dt.replace(tzinfo=ha_tz) if dt.tzinfo is None else dt

            start_date = _parse_date(request.query.get('start_date'))
            end_date   = _parse_date(request.query.get('end_date'))

            entries = self.hass.config_entries.async_entries(DOMAIN)
            if not entries:
                return web.Response(
                    text=json.dumps({'error': 'Integration not loaded'}),
                    content_type='application/json', status=404,
                )

            entry_obj = entries[0]

            # Set up SSE stream
            resp = web.StreamResponse(headers={
                'Content-Type': 'text/event-stream',
                'Cache-Control': 'no-cache',
                'X-Accel-Buffering': 'no',
                'Access-Control-Allow-Origin': '*',
            })
            await resp.prepare(request)

            async def send(event, data):
                try:
                    payload = f"event: {event}\ndata: {json.dumps(data, default=str)}\n\n"
                    await resp.write(payload.encode())
                except Exception:
                    pass  # client disconnected

            from .const import CONF_GRIDLENS_API_KEY, CONF_GRIDLENS_API_URL, CONF_STATE

            api_key = entry_obj.data.get(CONF_GRIDLENS_API_KEY, "")
            api_url = entry_obj.data.get(CONF_GRIDLENS_API_URL, "https://api.gridlens.au")
            state   = entry_obj.data.get(CONF_STATE, "NSW")
            network = entry_obj.data.get(CONF_DISTRIBUTOR, "")

            # Fetch plan data from API — enforces tier (free → locked plan only).
            _LOGGER.info("Fetching plans from API (state=%s, network=%s)", state, network)
            plan_data: dict = {}
            network_operators: dict = {}
            try:
                _session = async_get_clientsession(self.hass)
                async with _session.get(
                    f"{api_url}/plans",
                    params={"state": state, "current_plan": entry_obj.data.get("current_plan", ""), "network": network},
                    headers={"X-API-Key": api_key, "User-Agent": "GridLens-HA-Integration/1.0"},
                    timeout=aiohttp.ClientTimeout(total=15),
                ) as _r:
                    if _r.status == 200:
                        _resp = await _r.json()
                        plan_data = _resp.get("plans", {})
                        network_operators = _resp.get("network_operators", {})
                        _LOGGER.info("Loaded %d plan(s) from API (tier=%s)", len(plan_data), _resp.get("tier"))
                    elif _r.status == 402:
                        _body = await _r.text()
                        _LOGGER.warning("API /plans returned %s: %s", _r.status, _body[:200])
                        persistent_notification.async_create(
                            self.hass,
                            "Your Grid Lens subscription has ended and the dashboard cannot show plan data. "
                            "Please resubscribe at **gridlens.au/pricing** or reconfigure the integration "
                            "to restore your original plan.",
                            title="Grid Lens: Subscription Ended",
                            notification_id="grid_lens_subscription_ended",
                        )
                    else:
                        _body = await _r.text()
                        _LOGGER.warning("API /plans returned %s: %s", _r.status, _body[:200])
            except Exception as _exc:
                _LOGGER.warning("Could not fetch plan data from API: %s", _exc)

            plans_total = len(plan_data) or 1
            plans_done  = 0

            await send('status', {
                'phase': 'fetching',
                'message': 'Fetching energy data…',
                'plans_total': plans_total,
            })

            # Apply plan-history override if available
            from .plan_calculator import PlanCalculator
            calculator = PlanCalculator(self.hass, entry_obj)
            calculator.plan_data = plan_data
            calculator.network_operators = network_operators

            if start_date:
                from homeassistant.helpers.storage import Store
                hist_store = Store(self.hass, _HISTORY_STORAGE_VERSION, _HISTORY_STORAGE_KEY)
                hist_data  = await hist_store.async_load() or {"entries": []}
                hist_plan  = _plan_from_history(hist_data["entries"], start_date)
                if hist_plan:
                    calculator.current_plan_override = hist_plan

            async def on_plan_ready(plan_key, detail, meta):
                nonlocal plans_done
                plans_done += 1
                await send('plan', {
                    'plan_key':          plan_key,
                    'detail':            detail,
                    'plans_done':        plans_done,
                    'plans_total':       plans_total,
                    'current_plan_name': meta.get('current_plan_name'),
                    'alternative_plans': meta.get('alternative_plans', {}),
                    'current_plan_total': meta.get('current_plan_total', 0),
                    'usage_days':        meta.get('usage_days', 0),
                    'start_date':        meta.get('start_date', ''),
                    'end_date':          meta.get('end_date', ''),
                    'energy_flows':      meta.get('energy_flows', {}),
                    'deferrable_devices': meta.get('deferrable_devices', []),
                })

            async def on_fetch_progress(message, step, total):
                await send('status', {
                    'phase':       'fetching',
                    'message':     message,
                    'fetch_step':  step,
                    'fetch_total': total,
                    'plans_total': plans_total,
                })

            result = await calculator.calculate_plan_costs(
                start_date, end_date,
                on_plan_ready=on_plan_ready,
                on_progress=on_fetch_progress,
            )
            await send('complete', result)
            return resp

    class PowerflowCardView(HomeAssistantView):
        """Proxies the Power Flow card's JS from the API — gated on the install's
        ApiKey.powerflow_card entitlement (see gridlens-api/app/cards.py's
        GET /cards/powerflow). The browser never talks to the API directly and
        never sees the API key; this view fetches server-to-server (using the
        key stored in the config entry) and re-serves the result at a fixed,
        stable URL so the Lovelace resource never has to change.

        Caches per config entry for a TTL so a page reload / several open tabs
        don't each trigger a fresh API round-trip. On a genuine network failure,
        prefers re-serving a previously fetched REAL card over downgrading to
        the paywall stub — an API/LXC outage should never nag a paying customer;
        it should only ever fail toward "keeps showing what they already had".
        The paywall stub (powerflow_locked.LOCKED_CARD_JS) is only served on an
        explicit 401/402/403 (a real "not entitled" answer) or when nothing has
        ever been fetched successfully for this entry.
        """

        url = "/api/grid_lens/cards/grid-lens-powerflow-card.js"
        name = "api:grid_lens:powerflow_card"
        requires_auth = False

        _TTL_ENTITLED = 300   # seconds — a real subscription rarely lapses mid-session
        _TTL_LOCKED = 60      # shorter — so upgrading is reflected reasonably promptly

        def __init__(self, hass_instance):
            self.hass = hass_instance
            self._cache: dict[str, tuple] = {}  # entry_id -> (fetched_at, js_text, entitled)

        async def get(self, request):
            import time
            from .const import CONF_GRIDLENS_API_KEY, CONF_GRIDLENS_API_URL
            from .powerflow_locked import LOCKED_CARD_JS

            version = request.query.get("v", "")

            def _serve(js: str, entitled: bool) -> web.Response:
                text = js.replace("__CARD_VERSION__", version) if entitled else js
                return web.Response(text=text, content_type="application/javascript")

            entries = self.hass.config_entries.async_entries(DOMAIN)
            entry = entries[0] if entries else None
            if not entry:
                return _serve(LOCKED_CARD_JS, False)

            now = time.monotonic()
            cached = self._cache.get(entry.entry_id)
            if cached:
                fetched_at, js_text, entitled = cached
                ttl = self._TTL_ENTITLED if entitled else self._TTL_LOCKED
                if now - fetched_at < ttl:
                    return _serve(js_text, entitled)

            api_key = entry.data.get(CONF_GRIDLENS_API_KEY, "")
            api_url = entry.data.get(CONF_GRIDLENS_API_URL, "https://api.gridlens.au")
            try:
                session = async_get_clientsession(self.hass)
                async with session.get(
                    f"{api_url}/cards/powerflow",
                    headers={"X-API-Key": api_key, "User-Agent": "GridLens-HA-Integration/1.0"},
                    timeout=aiohttp.ClientTimeout(total=10),
                ) as resp:
                    if resp.status == 200:
                        js_raw = await resp.text()
                        self._cache[entry.entry_id] = (now, js_raw, True)
                        return _serve(js_raw, True)
                    if resp.status in (401, 402, 403):
                        self._cache[entry.entry_id] = (now, LOCKED_CARD_JS, False)
                        return _serve(LOCKED_CARD_JS, False)
                    _LOGGER.warning(
                        "Power Flow card: unexpected status %s from API", resp.status
                    )
            except Exception as err:  # noqa: BLE001 — network is best-effort here
                _LOGGER.warning("Power Flow card: could not reach API (%s)", err)

            # Network failure or an unexpected status: prefer stale-but-real over the
            # paywall — never punish a paying customer for an outage on our end.
            if cached and cached[2]:
                return _serve(cached[1], True)
            return _serve(LOCKED_CARD_JS, False)

    class PowerflowIconView(HomeAssistantView):
        """Proxies one of the Power Flow card's node icons from the API — same
        entitlement gate and server-to-server fetch pattern as PowerflowCardView
        above, just for a binary asset instead of JS. See that class's docstring
        for the browser-never-sees-the-API-key rationale, which applies here too.

        These icons moved here (from a static file under this integration's own
        www/icons/) 2026-08-05 — they'd been served publicly since before the
        card was gated, exclusively for this card's own use, undermining the
        exact protection this proxy exists to provide. See
        GRIDLENS_CHECKLIST.md's 2026-08-05 entry for the full story.

        Unlike the card JS, there's no "locked" placeholder image: if the
        install isn't entitled, the real diagram never renders in the first
        place (the paywall stub is a self-contained upsell UI with no node
        icons of its own), so nothing would ever request one of these URLs
        while un-entitled anyway. A 404 is a fine degradation for that case.
        """

        url = "/api/grid_lens/icons/{filename}"
        name = "api:grid_lens:powerflow_icon"
        requires_auth = False

        _TTL_ENTITLED = 3600  # icon bytes change far less often than card logic
        _TTL_LOCKED = 60      # still short, so an upgrade is reflected promptly

        def __init__(self, hass_instance):
            self.hass = hass_instance
            # (entry_id, filename) -> (fetched_at, content, content_type, entitled)
            self._cache: dict[tuple[str, str], tuple] = {}

        # The card JS appends a hand-bumped ?v= query string (ICON_V) to every icon
        # URL, changed whenever icon bytes change — so a given URL's content is
        # permanently fixed and safe to cache aggressively in the browser. Without
        # this, every request (including the query string) was refetched from HA on
        # every page load, since aiohttp's web.Response sends no cache headers by
        # default. That's most visible over the reverse-proxied FQDN path, where
        # these binary assets are also multiplexed as HTTP/2 streams over one
        # connection instead of the browser's parallel HTTP/1.1 connections used for
        # direct-IP access — repeated no-cache refetches compound that slowdown.
        _BROWSER_CACHE_HEADERS = {"Cache-Control": "public, max-age=31536000, immutable"}

        async def get(self, request, filename):
            import time
            from .const import CONF_GRIDLENS_API_KEY, CONF_GRIDLENS_API_URL

            entries = self.hass.config_entries.async_entries(DOMAIN)
            entry = entries[0] if entries else None
            if not entry:
                return web.Response(status=404)

            key = (entry.entry_id, filename)
            now = time.monotonic()
            cached = self._cache.get(key)
            if cached:
                fetched_at, content, content_type, entitled = cached
                ttl = self._TTL_ENTITLED if entitled else self._TTL_LOCKED
                if now - fetched_at < ttl:
                    return web.Response(
                        body=content, content_type=content_type,
                        headers=self._BROWSER_CACHE_HEADERS,
                    )

            api_key = entry.data.get(CONF_GRIDLENS_API_KEY, "")
            api_url = entry.data.get(CONF_GRIDLENS_API_URL, "https://api.gridlens.au")
            try:
                session = async_get_clientsession(self.hass)
                async with session.get(
                    f"{api_url}/cards/powerflow/icons/{filename}",
                    headers={"X-API-Key": api_key, "User-Agent": "GridLens-HA-Integration/1.0"},
                    timeout=aiohttp.ClientTimeout(total=10),
                ) as resp:
                    if resp.status == 200:
                        content = await resp.read()
                        content_type = resp.content_type
                        self._cache[key] = (now, content, content_type, True)
                        return web.Response(
                            body=content, content_type=content_type,
                            headers=self._BROWSER_CACHE_HEADERS,
                        )
                    if resp.status in (401, 402, 403, 404):
                        return web.Response(status=404)
                    _LOGGER.warning(
                        "Power Flow icon %s: unexpected status %s from API", filename, resp.status
                    )
            except Exception as err:  # noqa: BLE001 — network is best-effort here
                _LOGGER.warning("Power Flow icon %s: could not reach API (%s)", filename, err)

            # Network failure or an unexpected status: prefer stale-but-real over a
            # broken image, same principle as PowerflowCardView.
            if cached and cached[3]:
                return web.Response(
                    body=cached[1], content_type=cached[2],
                    headers=self._BROWSER_CACHE_HEADERS,
                )
            return web.Response(status=404)

    class SubscribeCallbackView(HomeAssistantView):
        """Receive subscription callback from gridlens.au and advance the config flow."""

        url = "/api/grid_lens/subscribe_callback"
        name = "api:grid_lens:subscribe_callback"
        requires_auth = False  # browser redirect from external site; flow_id is the token

        def __init__(self, hass_instance):
            self.hass = hass_instance

        async def get(self, request):
            flow_id = request.query.get("flow_id")
            api_key = request.query.get("api_key", "")

            if not flow_id:
                return web.Response(text="Missing flow_id.", status=400)

            self.hass.data.setdefault(DOMAIN, {}).setdefault(
                "pending_subscriptions", {}
            )[flow_id] = api_key

            try:
                await self.hass.config_entries.flow.async_configure(flow_id, {})
            except Exception as err:
                _LOGGER.warning("Could not advance subscribe flow %s: %s", flow_id, err)

            html = """<!DOCTYPE html>
<html>
<head>
  <title>Grid Lens</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body{font-family:sans-serif;display:flex;align-items:center;justify-content:center;
         height:100vh;margin:0;background:#1c1c1e;color:#fff}
    .card{text-align:center;padding:2rem}
    h1{font-size:1.5rem;margin-bottom:.5rem}
    p{color:#aaa}
  </style>
</head>
<body>
  <div class="card">
    <h1>You\'re all set!</h1>
    <p>Return to Home Assistant to complete setup.</p>
  </div>
  <script>if(window.opener){window.close()}</script>
</body>
</html>"""
            return web.Response(text=html, content_type="text/html")

    hass.http.register_view(PlanDataView(hass))
    hass.http.register_view(PlanHistoryView(hass))
    hass.http.register_view(PlanHistoryItemView(hass))
    hass.http.register_view(DiagnosticExportView(hass))
    hass.http.register_view(PlanStreamView(hass))
    hass.http.register_view(PowerflowCardView(hass))
    hass.http.register_view(PowerflowIconView(hass))
    hass.http.register_view(SubscribeCallbackView(hass))

    return True


async def _async_update_listener(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Reload the entry when its options/data change (Reconfigure). Needed so a newly
    assigned deferrable control switch (or any device config change) actually takes effect
    without a full HA restart — the control managers + platform entities are built at
    setup time from entry.data."""
    await hass.config_entries.async_reload(entry.entry_id)


async def _ensure_load_estimators(hass: HomeAssistant, entry: ConfigEntry) -> tuple[dict, dict]:
    """Two related pieces of automatic LoadEstimator wiring, both run once here at the
    top of async_setup_entry (see the ordering note below):

    1. **"Estimated load" slots** (CONF_DEFERRABLE_LOAD_EST_*) — a device with a control
       entity but no energy sensor at all (e.g. an IR-blaster aircon). Splices a synthetic
       energy sensor into the normal sensor-backed CONF_DEFERRABLE_LOAD_SENSORS lists so
       the rest of the system treats it exactly like a device with a real meter.
    2. **Power-only inference** (added 2026-08-02, no config beyond CONF_LOAD_POWER_SENSOR
       needed) — for EVERY deferrable device with a control entity but no live
       power_entity resolvable by entity_lookup.resolve_power_sensor() — the common case
       for a device whose only telemetry is a cumulative energy counter (e.g. an ECHONET
       Lite aircon's measured_cumulative_power_consumption, device_class energy not
       power) — builds a power-only LoadEstimator (track_energy=False; the real
       accumulation already comes from the device's own sensor, this is ONLY for a live
       W reading) so the Power Flow card, which silently drops any node with no
       power_entity, can show it. Covers both sensor-backed devices AND the
       estimated-load ones from step 1. Silently does nothing (per device) if
       CONF_LOAD_POWER_SENSOR isn't configured — same fail-open discipline as every
       other optional sensor in this integration. Calibrates off the device's OWN
       cumulative energy sensor (energy_sensor=sensor_id — that sensor is the reason the
       device reached step 2 at all) rather than the whole-house load sensor whenever one
       is present, so a second concurrent load (e.g. another HVAC unit's compressor
       cycling, invisible as a discrete state change) can't contaminate the estimate —
       see load_estimation.py's module docstring.

    Returns (energy_estimators, power_estimators):
    - energy_estimators: {est_slot_index: LoadEstimator} — sensor.py wraps each in a
      GridLensEstimatedEnergySensor.
    - power_estimators: {sensor_id: LoadEstimator} — sensor.py wraps each in a
      GridLensEstimatedPowerSensor, and _build_deferrable_loads() falls back to it as
      the device's power_entity when resolve_power_sensor() finds nothing. An
      estimated-load slot's estimator appears in BOTH dicts (the same LoadEstimator
      instance — it has neither a real energy nor a real power sensor).

    Must run before anything else in async_setup_entry reads entry.data
    (GridLensCoordinator, LoadControlManager, PlanCalculator, AdvisoryCoordinator, and the
    platform entities all do) and before the config-entry update listener is registered —
    the async_update_entry call below (step 1 only) is a one-time, idempotent merge (a
    no-op once a slot's sensor id is already present in CONF_DEFERRABLE_LOAD_SENSORS), and
    with no listener registered yet it can't race a reload against this very setup call:
    the merged entry.data is simply already correct by the time everything else below
    reads it. See const.py's CONF_DEFERRABLE_LOAD_EST_* docstring for the design step 1
    implements.
    """
    from homeassistant.helpers import entity_registry as er
    from homeassistant.util import slugify

    from .const import (
        CONF_DEFERRABLE_LOAD_CL_IN_AGGREGATE,
        CONF_DEFERRABLE_LOAD_CLIMATE_ON_MODE,
        CONF_DEFERRABLE_LOAD_CONTROLLED_LOAD,
        CONF_DEFERRABLE_LOAD_EST_AUTO,
        CONF_DEFERRABLE_LOAD_EST_CONTROL,
        CONF_DEFERRABLE_LOAD_EST_KW,
        CONF_DEFERRABLE_LOAD_EST_NAMES,
        CONF_DEFERRABLE_LOAD_MAX_KW,
        CONF_DEFERRABLE_LOAD_SOC_SENSORS,
        CONF_DEFERRABLE_LOAD_SWITCHES,
        CONF_LOAD_POWER_SENSOR,
    )
    from .entity_lookup import resolve_device_name, resolve_power_sensor
    from .load_estimation import EstimateStore, LoadEstimator

    load_power_sensor = entry.data.get(CONF_LOAD_POWER_SENSOR) or ""
    ent_reg = er.async_get(hass)
    store = EstimateStore(hass, entry.entry_id)

    sensors = list(entry.data.get(CONF_DEFERRABLE_LOAD_SENSORS, []) or [])
    max_kw_list = list(entry.data.get(CONF_DEFERRABLE_LOAD_MAX_KW, []) or [])
    switches_list = list(entry.data.get(CONF_DEFERRABLE_LOAD_SWITCHES, []) or [])
    climate_mode_list = list(entry.data.get(CONF_DEFERRABLE_LOAD_CLIMATE_ON_MODE, []) or [])
    soc_list = list(entry.data.get(CONF_DEFERRABLE_LOAD_SOC_SENSORS, []) or [])
    cl_list = list(entry.data.get(CONF_DEFERRABLE_LOAD_CONTROLLED_LOAD, []) or [])
    in_agg_list = list(entry.data.get(CONF_DEFERRABLE_LOAD_CL_IN_AGGREGATE, []) or [])
    # Every parallel list must stay the same length as `sensors` — relied on throughout
    # plan_calculator.py/LoadControlManager (index i always means "device i").
    _pairs = (
        (max_kw_list, 3.5), (switches_list, ""), (climate_mode_list, ""),
        (soc_list, ""), (cl_list, ""), (in_agg_list, False),
    )
    for lst, fill in _pairs:
        lst.extend([fill] * (len(sensors) - len(lst)))

    # ------------------------------------------------------------ step 1: estimated loads
    names = list(entry.data.get(CONF_DEFERRABLE_LOAD_EST_NAMES, []) or [])
    controls = list(entry.data.get(CONF_DEFERRABLE_LOAD_EST_CONTROL, []) or [])
    kws = list(entry.data.get(CONF_DEFERRABLE_LOAD_EST_KW, []) or [])
    autos = list(entry.data.get(CONF_DEFERRABLE_LOAD_EST_AUTO, []) or [])
    # Every control entity already known BEFORE constructing any estimator, so slot 0's
    # "others" list correctly includes slot 1/2's control entities even though they're
    # constructed later in the loop below.
    all_control_entities = [c for c in controls if c] + [s for s in switches_list if s]

    energy_estimators: dict[int, LoadEstimator] = {}
    power_estimators: dict[str, LoadEstimator] = {}
    changed = False
    for i, raw_name in enumerate(names):
        name = str(raw_name).strip()
        if not name:
            continue
        control = str(controls[i]).strip() if i < len(controls) else ""
        if not control:
            _LOGGER.warning(
                "Estimated deferrable load %r has no control entity configured — skipping",
                name,
            )
            continue
        seed_kw = float(kws[i]) if i < len(kws) and kws[i] not in (None, "") else 1.0
        auto = bool(autos[i]) if i < len(autos) else False

        unique_id = f"{entry.entry_id}_est_{i}"
        reg_entry = ent_reg.async_get_or_create(
            "sensor", DOMAIN, unique_id,
            suggested_object_id=f"{slugify(name)}_estimated_consumption",
            config_entry=entry,
        )
        sensor_id = reg_entry.entity_id
        power_reg_entry = ent_reg.async_get_or_create(
            "sensor", DOMAIN, f"{unique_id}_power",
            suggested_object_id=f"{slugify(name)}_estimated_power",
            config_entry=entry,
        )

        others = [e for e in all_control_entities if e != control]
        estimator = LoadEstimator(
            hass, store=store, store_key=unique_id, name=name,
            control_entity_id=control, seed_kw=seed_kw, auto_refine=auto,
            load_power_sensor=load_power_sensor, other_control_entity_ids=others,
        )
        # Metadata only (never read internally by LoadEstimator) — the power sensor
        # entity sensor.py should wrap around this same estimator. See the class
        # docstring's "power_sensor_entity_id" note.
        estimator.power_unique_id = f"{unique_id}_power"
        estimator.power_sensor_entity_id = power_reg_entry.entity_id
        energy_estimators[i] = estimator
        power_estimators[sensor_id] = estimator

        if sensor_id not in sensors:
            sensors.append(sensor_id)
            max_kw_list.append(seed_kw)
            switches_list.append(control)
            climate_mode_list.append("")
            soc_list.append("")
            cl_list.append("")
            in_agg_list.append(False)
            changed = True

    if changed:
        hass.config_entries.async_update_entry(entry, data={
            **entry.data,
            CONF_DEFERRABLE_LOAD_SENSORS: sensors,
            CONF_DEFERRABLE_LOAD_MAX_KW: max_kw_list,
            CONF_DEFERRABLE_LOAD_SWITCHES: switches_list,
            CONF_DEFERRABLE_LOAD_CLIMATE_ON_MODE: climate_mode_list,
            CONF_DEFERRABLE_LOAD_SOC_SENSORS: soc_list,
            CONF_DEFERRABLE_LOAD_CONTROLLED_LOAD: cl_list,
            CONF_DEFERRABLE_LOAD_CL_IN_AGGREGATE: in_agg_list,
        })

    # ------------------------------------------------------- step 2: power-only inference
    # `switches_list` is now final (real devices + any estimated-load ones just spliced
    # in above), so this "others" set covers the whole household.
    if load_power_sensor:
        all_control_entities_final = [s for s in switches_list if s]
        for i, sensor_id in enumerate(sensors):
            if sensor_id in power_estimators:
                continue  # an estimated-load device — already covered in step 1
            control = switches_list[i] if i < len(switches_list) else ""
            if not control:
                continue  # forecast-only device, nothing to actuate/watch transitions on
            try:
                existing_power = resolve_power_sensor(hass, sensor_id, control)
            except Exception:  # noqa: BLE001 — discovery is best-effort
                existing_power = None
            if existing_power:
                continue  # already has real live power telemetry — nothing to estimate
            name = resolve_device_name(hass, control, sensor_id) or sensor_id
            seed_kw = float(max_kw_list[i]) if i < len(max_kw_list) else 1.0
            unique_id = f"{entry.entry_id}_pwr_{i}"
            reg_entry = ent_reg.async_get_or_create(
                "sensor", DOMAIN, unique_id,
                suggested_object_id=f"{slugify(name)}_estimated_power",
                config_entry=entry,
            )
            others = [e for e in all_control_entities_final if e != control]
            estimator = LoadEstimator(
                hass, store=store, store_key=unique_id, name=name,
                control_entity_id=control, seed_kw=seed_kw, auto_refine=True,
                load_power_sensor=load_power_sensor, other_control_entity_ids=others,
                track_energy=False,
                # sensor_id is by construction a cumulative energy sensor here (the whole
                # reason this device reached step 2 is that it has no live power_entity) —
                # calibrate the live-W estimate off the device's own meter rather than the
                # whole-house load sensor, so a second concurrent load (e.g. another HVAC
                # unit) can't contaminate it. See load_estimation.py's module docstring.
                energy_sensor=sensor_id,
            )
            estimator.power_unique_id = unique_id
            estimator.power_sensor_entity_id = reg_entry.entity_id
            power_estimators[sensor_id] = estimator

    # An estimated-load estimator is referenced from both dicts (same instance) —
    # load/start each unique estimator exactly once.
    unique_estimators: list[LoadEstimator] = []
    seen = set()
    for estimator in [*energy_estimators.values(), *power_estimators.values()]:
        if id(estimator) not in seen:
            seen.add(id(estimator))
            unique_estimators.append(estimator)
    for estimator in unique_estimators:
        await estimator.async_load()
        estimator.start()

    return energy_estimators, power_estimators


async def _notify_unpainted_climate_schedules(hass: HomeAssistant, entry: ConfigEntry, sched_store) -> None:
    """Nudge for a climate.*-controlled deferrable load (aircon) with no painted weekly
    schedule (§8 in FEATURES.md).

    A device with no stored grid is fully unrestricted — any hour — which is a reasonable
    default for a pool pump or EV charger (their daily energy genuinely can land anywhere),
    but not for an air conditioner: comfort, not price, decides when it needs to run, so an
    unpainted aircon lets the optimiser assume it can shift a whole day's runtime to 3am in
    both plan comparison and the real dispatch/control plan (same LP, FEATURES.md §0/§2).
    Runs once per setup/reload; re-evaluates every time so the notification clears itself
    once every climate.*-backed device has a schedule painted.
    """
    from .const import CONF_DEFERRABLE_LOAD_SENSORS, CONF_DEFERRABLE_LOAD_SWITCHES
    from .entity_lookup import resolve_device_name

    sensors = list(entry.data.get(CONF_DEFERRABLE_LOAD_SENSORS, []) or [])
    switches = list(entry.data.get(CONF_DEFERRABLE_LOAD_SWITCHES, []) or [])
    notification_id = f"grid_lens_unpainted_climate_schedule_{entry.entry_id}"

    unpainted = []
    for i, sensor_id in enumerate(sensors):
        control = switches[i] if i < len(switches) else ""
        if not control.startswith("climate."):
            continue
        if await sched_store.async_get(sensor_id) is not None:
            continue  # already painted
        unpainted.append(resolve_device_name(hass, control, sensor_id) or control)

    if not unpainted:
        persistent_notification.async_dismiss(hass, notification_id)
        return

    device_list = "\n".join(f"- {name}" for name in unpainted)
    persistent_notification.async_create(
        hass,
        "A deferrable load with no painted schedule is treated as reschedulable to **any "
        "hour** — reasonable for a pool pump or EV charger, but usually wrong for an air "
        "conditioner, since you run it for real-time comfort, not to chase the cheapest "
        "hour. Without a schedule, plan comparisons and the dispatch plan may assume it "
        f"could run at 3am.\n\nPaint allowed run times for:\n{device_list}\n\non the "
        "**Deferrable Loads** dashboard card's weekly schedule.",
        title="Grid Lens: Set aircon run-time hours",
        notification_id=notification_id,
    )


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up Grid Lens from a config entry."""
    _LOGGER.info("Setting up Grid Lens")

    hass.data.setdefault(DOMAIN, {})

    # Must run first, before anything below reads entry.data and before the update
    # listener is registered (see _ensure_load_estimators's own docstring for why).
    _energy_estimators, _power_estimators = await _ensure_load_estimators(hass, entry)
    hass.data[DOMAIN][f"{entry.entry_id}_load_estimators"] = _energy_estimators
    hass.data[DOMAIN][f"{entry.entry_id}_power_estimators"] = _power_estimators

    coordinator = GridLensCoordinator(hass, entry)
    hass.data[DOMAIN][entry.entry_id] = coordinator
    entry.async_on_unload(entry.add_update_listener(_async_update_listener))

    # Per-day deferrable load overrides (Feature 2) — independent of battery/control,
    # shared between the number.py entities and AdvisoryCoordinator. Created before the
    # platforms are forwarded so number.py can look it up during its own setup.
    from .deferrable_overrides import DeferrableOverrideStore
    hass.data[DOMAIN][f"{entry.entry_id}_deferrable_overrides"] = DeferrableOverrideStore(
        hass, entry.entry_id
    )

    # Weekly per-weekday availability schedules for deferrable loads (edited on the
    # dashboard schedule card; replaces the static hours config when set for a device).
    # Preloaded here so sensor.py's sync attribute builder can read the cache.
    from .deferrable_schedules import DeferrableScheduleStore
    _sched_store = DeferrableScheduleStore(hass, entry.entry_id)
    await _sched_store.async_load()
    hass.data[DOMAIN][f"{entry.entry_id}_deferrable_schedules"] = _sched_store

    await _notify_unpainted_climate_schedules(hass, entry, _sched_store)

    # GridLens-owned daily energy archive: captures per-day PV/import/export totals
    # into HA Storage so long-horizon features never depend on the user's recorder
    # retention (backfills from long-term statistics, then appends nightly).
    try:
        from homeassistant.helpers.event import async_track_time_change

        from .daily_archive import DailyEnergyArchive
        _archive = DailyEnergyArchive(hass, entry)
        hass.data[DOMAIN][f"{entry.entry_id}_daily_archive"] = _archive
        entry.async_create_background_task(
            hass, _archive.async_backfill(), name="grid_lens_daily_archive_backfill"
        )
        # 00:20 local: late enough that the recorder has compiled yesterday's last
        # daily-statistics bucket, early enough to be ready for morning planning.
        entry.async_on_unload(
            async_track_time_change(
                hass,
                lambda now: entry.async_create_background_task(
                    hass, _archive.async_daily_tick(now), name="grid_lens_daily_archive_tick"
                ),
                hour=0,
                minute=20,
                second=0,
            )
        )
    except Exception as _arch_err:  # noqa: BLE001
        _LOGGER.warning("Daily energy archive setup failed: %s", _arch_err)

    # Advisory mode (forecast-fed planning, read-only). Independent coordinator so it
    # never disturbs the manual plan-comparison flow. Best-effort — failures don't block.
    try:
        from .advisory.coordinator import AdvisoryCoordinator
        _adv = AdvisoryCoordinator(hass, entry)
        # Seed the last persisted plan BEFORE the sensor platform is set up, so the card
        # renders the previous plan instantly on restart instead of sitting blank until
        # live SOC/forecast arrive (Sigen Modbus SOC can take minutes to appear).
        await _adv.async_load_cached()
        hass.data[DOMAIN][f"{entry.entry_id}_advisory"] = _adv
    except Exception as _adv_err:  # noqa: BLE001
        _LOGGER.warning("Advisory mode setup failed: %s", _adv_err)

    # Battery control manager (actuation). Created but INERT until the master switch is
    # turned on — no charge/discharge writes on setup (the one exception is pushing the
    # hardware safety floor below, which is a passive bound, not an actuation). Deadman
    # restores native EMS on disable/stop.
    if entry.data.get("has_battery", False):
        try:
            from .control.manager import ControlManager
            _ctl_mgr = ControlManager(hass, entry)
            hass.data[DOMAIN][f"{entry.entry_id}_control"] = _ctl_mgr
            # Restore user intent (persisted independently of the switch entity's own
            # restore-state — see ControlManager.async_initialize()'s docstring) before
            # the switch platform is forwarded, so its initial displayed state is
            # already correct rather than defaulting off and flipping on moments later.
            await _ctl_mgr.async_initialize()
            # Push the hardware discharge floor now rather than waiting for the first
            # force_discharge() call — closes the window where a restart leaves the
            # floor software-only. Best-effort: if the inverter's entity surface isn't
            # up yet, the advisory coordinator's periodic tick retries this until it
            # lands (see AdvisoryCoordinator._refresh_meta).
            await _ctl_mgr.async_push_safety_floor()
        except Exception as _ctl_err:  # noqa: BLE001
            _LOGGER.warning("Battery control setup failed: %s", _ctl_err)

    # Deferrable-load control manager (actuation for on/off AND modulating loads). Independent
    # of has_battery — created whenever any deferrable device has a control entity configured,
    # which since the modulating-load feature means a control switch OR a current/power
    # setpoint. has_controllable() is the single test for that: the manager builds one
    # controller per device of either type into the same dict, so no separate setpoint check
    # is needed here. INERT until its per-device master switch is turned on (default OFF); no
    # switch or setpoint writes on setup. Deadman = leave loads as-is (never forces off).
    try:
        from .control.load_control_manager import LoadControlManager
        _load_mgr = LoadControlManager(hass, entry)
        if _load_mgr.has_controllable():
            hass.data[DOMAIN][f"{entry.entry_id}_load_control"] = _load_mgr
    except Exception as _load_err:  # noqa: BLE001
        _LOGGER.warning("Deferrable load control setup failed: %s", _load_err)

    # Register services
    from .services import async_setup_services
    await async_setup_services(hass, entry)

    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

    # Pre-calculate in the background so the card has data immediately on load. The
    # advisory refresh is chained AFTER the main one (awaited), because it reads the
    # main coordinator's plan_data — running them concurrently races and leaves the
    # advisory sensor stuck "waiting" until its next 10-min tick.
    async def _startup_refresh():
        await coordinator.async_refresh()
        _advisory = hass.data[DOMAIN].get(f"{entry.entry_id}_advisory")
        if _advisory is not None:
            await _advisory.async_refresh()

    hass.async_create_task(_startup_refresh())

    return True


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Unload a config entry."""
    # Deadman: if battery control is active, restore native EMS before tearing down.
    # Uses async_prepare_for_reload(), NOT disable() — this fires on every reload
    # regardless of user intent, so it must not clear the persisted "want enabled"
    # flag (see ControlManager.async_initialize()'s docstring for the incident that
    # caused when this used disable()).
    _mgr = hass.data.get(DOMAIN, {}).get(f"{entry.entry_id}_control")
    if _mgr is not None:
        try:
            await _mgr.async_prepare_for_reload()
        except Exception:  # noqa: BLE001
            pass

    # Load control deadman = leave loads as-is: stop ticking, never force a switch off.
    _load_mgr = hass.data.get(DOMAIN, {}).get(f"{entry.entry_id}_load_control")
    if _load_mgr is not None:
        try:
            _load_mgr.shutdown()
        except Exception:  # noqa: BLE001
            pass

    # Stop each estimator's listeners/timers — nothing to actuate on teardown, this is
    # just cancelling background work (unlike battery/load control, no deadman needed).
    # An estimated-load estimator lives in both dicts (same instance) — stop each unique
    # one exactly once.
    _energy_ests = hass.data.get(DOMAIN, {}).get(f"{entry.entry_id}_load_estimators", {})
    _power_ests = hass.data.get(DOMAIN, {}).get(f"{entry.entry_id}_power_estimators", {})
    _seen_est_ids: set = set()
    for _est in [*_energy_ests.values(), *_power_ests.values()]:
        if id(_est) in _seen_est_ids:
            continue
        _seen_est_ids.add(id(_est))
        try:
            _est.stop()
        except Exception:  # noqa: BLE001
            pass

    if unload_ok := await hass.config_entries.async_unload_platforms(entry, PLATFORMS):
        hass.data[DOMAIN].pop(entry.entry_id)
        hass.data[DOMAIN].pop(f"{entry.entry_id}_advisory", None)
        hass.data[DOMAIN].pop(f"{entry.entry_id}_control", None)
        hass.data[DOMAIN].pop(f"{entry.entry_id}_load_control", None)
        hass.data[DOMAIN].pop(f"{entry.entry_id}_deferrable_overrides", None)
        hass.data[DOMAIN].pop(f"{entry.entry_id}_deferrable_schedules", None)
        hass.data[DOMAIN].pop(f"{entry.entry_id}_load_estimators", None)
        hass.data[DOMAIN].pop(f"{entry.entry_id}_power_estimators", None)

    return unload_ok


class GridLensCoordinator(DataUpdateCoordinator):
    """Coordinator to manage electricity plan comparison data."""

    def __init__(self, hass: HomeAssistant, entry: ConfigEntry) -> None:
        """Initialize coordinator."""
        super().__init__(
            hass,
            _LOGGER,
            name=DOMAIN,
            update_interval=None,  # Manual refresh only — never auto-calculate
        )
        self.entry = entry
        self.hass = hass
        self.calculator = None  # Will be created on first update
        self.energy_dashboard_names: dict[str, str] = {}

    async def _async_update_data(self):
        """Fetch data from energy sensors and calculate plan comparisons."""
        import aiohttp
        from .plan_calculator import PlanCalculator
        from .const import CONF_GRIDLENS_API_KEY, CONF_GRIDLENS_API_URL, CONF_STATE
        from .entity_lookup import async_get_energy_dashboard_names

        self.energy_dashboard_names = await async_get_energy_dashboard_names(self.hass)

        api_key = self.entry.data.get(CONF_GRIDLENS_API_KEY, "")
        api_url = self.entry.data.get(CONF_GRIDLENS_API_URL, "https://api.gridlens.au")
        state   = self.entry.data.get(CONF_STATE, "NSW")
        network = self.entry.data.get(CONF_DISTRIBUTOR, "")

        plan_data: dict = {}
        network_operators: dict = {}
        try:
            import aiohttp as _aiohttp
            _session = async_get_clientsession(self.hass)
            async with _session.get(
                f"{api_url}/plans",
                params={"state": state, "current_plan": self.entry.data.get("current_plan", ""), "network": network},
                headers={"X-API-Key": api_key, "User-Agent": "GridLens-HA-Integration/1.0"},
                timeout=_aiohttp.ClientTimeout(total=15),
            ) as _r:
                if _r.status == 200:
                    _resp = await _r.json()
                    plan_data = _resp.get("plans", {})
                    network_operators = _resp.get("network_operators", {})
                elif _r.status == 402:
                    _LOGGER.warning("Coordinator: API /plans returned 402 (subscription ended)")
                    persistent_notification.async_create(
                        self.hass,
                        "Your Grid Lens subscription has ended and the dashboard cannot show plan data. "
                        "Please resubscribe at **gridlens.au/pricing** or reconfigure the integration "
                        "to restore your original plan.",
                        title="Grid Lens: Subscription Ended",
                        notification_id="grid_lens_subscription_ended",
                    )
                else:
                    _LOGGER.warning("Coordinator: API /plans returned %s", _r.status)
        except Exception as _exc:
            _LOGGER.warning("Coordinator: could not fetch plan data: %s", _exc)

        self.calculator = PlanCalculator(self.hass, self.entry)
        self.calculator.plan_data = plan_data
        self.calculator.network_operators = network_operators
        result = await self.calculator.calculate_plan_costs()
        _LOGGER.info(f"Plan calculation complete: {result.get('usage_days', 0)} days")

        # Build per-plan sensor data for CoordinatorEntity sensors
        plan_metrics = {}
        plan_details = result.get("plan_details", {})
        for plan_id, plan_key in PLAN_ID_TO_KEY.items():
            detail = plan_details.get(plan_key, {})
            opt = detail.get("optimization", {})
            schedule = opt.get("schedule", [])

            total_import = opt.get("total_import_kwh", 0.0) or 0.0
            total_export = opt.get("total_export_kwh", 0.0) or 0.0
            total_import_cost = opt.get("total_import_cost", 0.0) or 0.0
            total_export_credit = opt.get("total_export_credit", 0.0) or 0.0
            total_charge = sum(h.get("charge_kwh", 0) for h in schedule)
            total_discharge = sum(h.get("discharge_kwh", 0) for h in schedule)
            net_cost = opt.get("net_cost", detail.get("breakdown", {}).get("total", 0.0)) or 0.0

            plan_metrics[plan_id] = {
                "grid_import": round(total_import, 3),
                "grid_export": round(total_export, 3),
                "battery_charge": round(total_charge, 3),
                "battery_discharge": round(total_discharge, 3),
                "solar_production": 0.0,
                "buy_price": round(total_import_cost / total_import, 4) if total_import else 0.0,
                "sell_price": round(total_export_credit / total_export, 4) if total_export else 0.0,
                "hourly_cost": round(net_cost / len(schedule), 4) if schedule else 0.0,
                "optimization_notes": detail.get("strategy", ""),
            }

        result["plan_metrics"] = plan_metrics
        return result
