"""Grid Lens Integration."""
from __future__ import annotations

import logging

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import Platform
from homeassistant.core import HomeAssistant
import aiohttp
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator
from homeassistant.helpers.aiohttp_client import async_get_clientsession

from .const import DOMAIN, PLAN_ID_TO_KEY

_LOGGER = logging.getLogger(__name__)

PLATFORMS: list[Platform] = [Platform.SENSOR]

_HISTORY_STORAGE_KEY = "grid_lens_plan_history"
_HISTORY_STORAGE_VERSION = 1

_DIAGNOSTIC_README = """\
Grid Lens — Diagnostic Export
================================================
Generated by the Home Assistant 'grid_lens' integration.
Share this file when reporting a bug. No credentials or API keys are included —
only entity IDs and energy statistics.

Contents:
  README.txt                — This file
  info.json                 — HA version, calculation period, configured sensor entity IDs
  config.json               — Battery and deferrable load configuration
  plan_rates.json           — All plan rate structures used in the calculation
  calculation_summary.json  — Per-plan costs and savings vs current plan
  energy_flows.json         — Hourly energy flows (first 24 hours of period)
  plans/<plan>.json         — Per-plan LP schedules, bill breakdowns, hourly profiles
"""


def _plan_from_history(entries: list, start_date) -> str | None:
    """Return the plan name active at start_date (latest entry whose date <= start_date)."""
    query = start_date.date().isoformat() if hasattr(start_date, 'date') else str(start_date)[:10]
    active = None
    for entry in sorted(entries, key=lambda e: e['date']):
        if entry['date'] <= query:
            active = entry['plan_name']
    return active


async def async_setup(hass: HomeAssistant, config: dict) -> bool:
    """Set up the Grid Lens component."""
    import pathlib
    import uuid as _uuid
    from homeassistant.helpers.storage import Store
    from homeassistant.const import EVENT_HOMEASSISTANT_STARTED

    # Serve www/ directly from the integration directory
    www_path = str(pathlib.Path(__file__).parent / "www")
    try:
        from homeassistant.components.http import StaticPathConfig
        await hass.http.async_register_static_paths(
            [StaticPathConfig("/grid_lens", www_path, False)]
        )
    except Exception as e:
        _LOGGER.warning("Could not register static path for Grid Lens: %s", e)

    # Register Lovelace resource modules using the runtime collection (like simple_timer)
    # This ensures the frontend is notified immediately and stale entries are cleaned up.
    card_urls = [
        "/grid_lens/cards/grid-lens-card.js",
        "/grid_lens/cards/grid-lens-flow-card.js",
    ]
    stale_urls = {
        "/grid_lens/cards/electricity-plan-comparison-card.js",
        "/grid_lens/cards/electricity-energy-flow-card.js",
        "/local/grid-lens/electricity-energy-flow-card.js",
        "/local/grid-lens/electricity-plan-comparison-card.js",
    }
    try:
        lovelace_data = hass.data.get("lovelace")
        if lovelace_data and hasattr(lovelace_data, "resources"):
            resources = lovelace_data.resources
            await resources.async_get_info()
            # Remove stale entries
            for item in list(resources.async_items()):
                if item.get("url", "").split("?")[0] in stale_urls:
                    try:
                        await resources.async_delete_item(item["id"])
                    except Exception:
                        pass
            # Add new entries if not already present
            existing = {item.get("url", "").split("?")[0] for item in resources.async_items()}
            for url in card_urls:
                if url not in existing:
                    await resources.async_create_item({"res_type": "module", "url": url})
        else:
            # Fallback: write directly to store
            resources_store = Store(hass, 1, "lovelace_resources")
            data = await resources_store.async_load() or {"items": []}
            data["items"] = [i for i in data["items"] if i["url"] not in stale_urls]
            existing_urls = {item["url"] for item in data["items"]}
            for url in card_urls:
                if url not in existing_urls:
                    data["items"].append({"id": str(_uuid.uuid4()), "type": "module", "url": url})
            await resources_store.async_save(data)
    except Exception as e:
        _LOGGER.warning("Could not register Lovelace resources for Grid Lens: %s", e)

    # Auto-register the Grid Lens dashboard in the sidebar
    async def _register_dashboard(_event=None):
        lovelace_data = hass.data.get("lovelace")
        if not lovelace_data or not hasattr(lovelace_data, "dashboards"):
            _LOGGER.warning("Grid Lens: lovelace not available, skipping dashboard registration")
            return
        try:
            dashboards = lovelace_data.dashboards

            dashboard_config = {
                "id": "grid_lens",
                "icon": "mdi:transmission-tower",
                "title": "Grid Lens",
                "url_path": "grid-lens",
                "require_admin": False,
                "mode": "storage",
                "show_in_sidebar": True,
            }

            # Persist to lovelace_dashboards store (read by HA on next startup)
            dash_store = Store(hass, 1, "lovelace_dashboards")
            dash_data = await dash_store.async_load() or {"items": []}
            already_stored = any(d.get("url_path") == "grid-lens" for d in dash_data.get("items", []))
            if not already_stored:
                dash_data.setdefault("items", []).append(dashboard_config)
                await dash_store.async_save(dash_data)

            # Seed dashboard content if not yet created
            content_store = Store(hass, 1, "lovelace.grid_lens")
            if not await content_store.async_load():
                await content_store.async_save({
                    "config": {
                        "title": "Grid Lens",
                        "views": [{
                            "type": "panel",
                            "title": "Plan Comparison",
                            "path": "plan-comparison",
                            "cards": [{
                                "type": "custom:grid-lens-card",
                                "entity": "sensor.grid_lens_amber_monthly_cost",
                            }]
                        }]
                    }
                })

            # If already registered in-memory, nothing more to do
            if isinstance(dashboards, dict) and "grid-lens" in dashboards:
                return
            if not isinstance(dashboards, dict) and any(
                d.get("url_path") == "grid-lens" for d in dashboards.async_items()
            ):
                return

            # In HA 2026 dashboards is a plain dict; try adding the LovelaceStorage
            # object directly so the sidebar updates without a restart.
            if isinstance(dashboards, dict):
                try:
                    from homeassistant.components.lovelace.dashboard import LovelaceStorage as _LS
                    dashboards["grid-lens"] = _LS(hass, dashboard_config)
                    _LOGGER.info("Grid Lens dashboard added to sidebar")
                except Exception:
                    _LOGGER.info("Grid Lens dashboard written to storage — will appear in sidebar after next HA restart")
            else:
                await dashboards.async_create_item(dashboard_config)
                _LOGGER.info("Grid Lens dashboard registered in sidebar")
        except Exception as e:
            _LOGGER.warning("Could not register Grid Lens dashboard: %s", e)

    if hass.is_running:
        hass.async_create_task(_register_dashboard())
    else:
        hass.bus.async_listen_once(EVENT_HOMEASSISTANT_STARTED, _register_dashboard)

    from aiohttp import web
    from homeassistant.components.http import HomeAssistantView

    class PlanDataView(HomeAssistantView):
        """Serve plan optimization data for dashboard."""
        
        url = "/api/grid_lens/plan_data"
        name = "api:grid_lens:plan_data"
        requires_auth = False
        
        def __init__(self, hass_instance):
            self.hass = hass_instance
        
        async def get(self, request):
            """Get plan optimization data with optional date range."""
            import json
            from datetime import datetime

            # Parse dates in the HA configured timezone so "May 12 00:00" means
            # local midnight, not UTC midnight (which would be wrong for AEST).
            try:
                from zoneinfo import ZoneInfo
            except ImportError:
                from backports.zoneinfo import ZoneInfo
            ha_tz = ZoneInfo(self.hass.config.time_zone or "UTC")

            start_date_str = request.query.get('start_date')
            end_date_str = request.query.get('end_date')
            start_date = None
            end_date = None

            if start_date_str:
                try:
                    start_date = datetime.fromisoformat(
                        start_date_str.replace('Z', '+00:00')
                    )
                    if start_date.tzinfo is None:
                        start_date = start_date.replace(tzinfo=ha_tz)
                except ValueError:
                    return web.Response(
                        text=json.dumps({'error': 'Invalid start_date format'}),
                        content_type='application/json',
                        status=400
                    )

            if end_date_str:
                try:
                    end_date = datetime.fromisoformat(
                        end_date_str.replace('Z', '+00:00')
                    )
                    if end_date.tzinfo is None:
                        end_date = end_date.replace(tzinfo=ha_tz)
                except ValueError:
                    return web.Response(
                        text=json.dumps({'error': 'Invalid end_date format'}),
                        content_type='application/json',
                        status=400
                    )

            entries = self.hass.config_entries.async_entries(DOMAIN)
            if not entries:
                return web.Response(
                    text=json.dumps({'error': 'Integration not loaded'}),
                    content_type='application/json',
                    status=404
                )

            coordinator = self.hass.data.get(DOMAIN, {}).get(entries[0].entry_id)
            if not coordinator:
                return web.Response(
                    text=json.dumps({'error': 'No coordinator'}),
                    content_type='application/json',
                    status=404
                )

            # Custom date range: recalculate on-the-fly and return directly.
            if start_date or end_date:
                import aiohttp as _aiohttp
                from .plan_calculator import PlanCalculator
                from .const import CONF_GRIDLENS_API_KEY, CONF_GRIDLENS_API_URL, CONF_STATE
                from homeassistant.helpers.storage import Store
                entries = self.hass.config_entries.async_entries(DOMAIN)
                entry_obj = entries[0] if entries else None
                if not entry_obj:
                    return web.Response(text=json.dumps({'error': 'No entry'}), content_type='application/json', status=404)
                _api_key = entry_obj.data.get(CONF_GRIDLENS_API_KEY, "")
                _api_url = entry_obj.data.get(CONF_GRIDLENS_API_URL, "https://api.gridlens.au")
                _state   = entry_obj.data.get(CONF_STATE, "NSW")
                _plan_data: dict = {}
                try:
                    _sess = async_get_clientsession(self.hass)
                    async with _sess.get(f"{_api_url}/plans", params={"state": _state},
                                         headers={"X-API-Key": _api_key, "User-Agent": "GridLens-HA-Integration/1.0"},
                                         timeout=_aiohttp.ClientTimeout(total=15)) as _r:
                        if _r.status == 200:
                            _plan_data = (await _r.json()).get("plans", {})
                except Exception as _exc:
                    _LOGGER.warning("plan-rates: could not fetch plan data: %s", _exc)
                calculator = PlanCalculator(self.hass, entry_obj)
                calculator.plan_data = _plan_data

                # Derive which plan the user was actually on at start_date from change history.
                if start_date:
                    _hist_store = Store(self.hass, _HISTORY_STORAGE_VERSION, _HISTORY_STORAGE_KEY)
                    _hist_data = await _hist_store.async_load() or {"entries": []}
                    _hist_plan = _plan_from_history(_hist_data["entries"], start_date)
                    if _hist_plan:
                        calculator.current_plan_override = _hist_plan
                        _LOGGER.info("History: current plan at %s is %s", start_date.date(), _hist_plan)

                response_data = await calculator.calculate_plan_costs(start_date, end_date)
                _LOGGER.info(f"Custom date range calculation complete: {response_data.get('usage_days')} days")
                return web.Response(
                    text=json.dumps(response_data),
                    content_type='application/json'
                )

            # Default: use coordinator cached data (populated on startup).
            if not coordinator.data:
                return web.Response(
                    text=json.dumps({'status': 'calculating'}),
                    content_type='application/json',
                    status=202
                )

            plan_details = coordinator.data.get('plan_details', {})
            response_data = {
                'plan_details': plan_details,
                'energy_flows': coordinator.data.get('energy_flows', {}),
                'amber_total': coordinator.data.get('amber_total', 0),
                'current_plan_name': coordinator.data.get('current_plan_name'),
                'deferrable_devices': coordinator.data.get('deferrable_devices', []),
                'usage_days': coordinator.data.get('usage_days', 0),
                'start_date': coordinator.data.get('start_date', ''),
                'end_date': coordinator.data.get('end_date', ''),
                'calculation_date': coordinator.data.get('calculation_date', ''),
            }

            return web.Response(
                text=json.dumps(response_data),
                content_type='application/json'
            )
    
    class PlanHistoryView(HomeAssistantView):
        """List and create plan change history entries."""

        url = "/api/grid_lens/plan_history"
        name = "api:grid_lens:plan_history"
        requires_auth = False

        def __init__(self, hass_instance):
            self.hass = hass_instance

        async def get(self, request):
            import json
            from homeassistant.helpers.storage import Store
            store = Store(self.hass, _HISTORY_STORAGE_VERSION, _HISTORY_STORAGE_KEY)
            data = await store.async_load() or {"entries": []}
            return web.Response(text=json.dumps(data), content_type='application/json')

        async def post(self, request):
            import json, uuid
            from homeassistant.helpers.storage import Store
            try:
                body = await request.json()
            except Exception:
                return web.Response(text=json.dumps({'error': 'Invalid JSON'}),
                                    content_type='application/json', status=400)
            if not body.get('date') or not body.get('plan_name'):
                return web.Response(text=json.dumps({'error': 'date and plan_name required'}),
                                    content_type='application/json', status=400)
            store = Store(self.hass, _HISTORY_STORAGE_VERSION, _HISTORY_STORAGE_KEY)
            data = await store.async_load() or {"entries": []}
            entry = {
                "id": str(uuid.uuid4()),
                "date": body['date'],
                "plan_name": body['plan_name'],
                "notes": body.get('notes', ''),
            }
            data["entries"].append(entry)
            await store.async_save(data)
            return web.Response(text=json.dumps({"entry": entry}), content_type='application/json')

    class PlanHistoryItemView(HomeAssistantView):
        """Update and delete individual plan change history entries."""

        url = "/api/grid_lens/plan_history/{entry_id}"
        name = "api:grid_lens:plan_history_item"
        requires_auth = False

        def __init__(self, hass_instance):
            self.hass = hass_instance

        async def put(self, request, entry_id):
            import json
            from homeassistant.helpers.storage import Store
            try:
                body = await request.json()
            except Exception:
                return web.Response(text=json.dumps({'error': 'Invalid JSON'}),
                                    content_type='application/json', status=400)
            store = Store(self.hass, _HISTORY_STORAGE_VERSION, _HISTORY_STORAGE_KEY)
            data = await store.async_load() or {"entries": []}
            for i, entry in enumerate(data["entries"]):
                if entry["id"] == entry_id:
                    data["entries"][i] = {
                        "id": entry_id,
                        "date": body.get('date', entry['date']),
                        "plan_name": body.get('plan_name', entry['plan_name']),
                        "notes": body.get('notes', entry.get('notes', '')),
                    }
                    await store.async_save(data)
                    return web.Response(text=json.dumps({"entry": data["entries"][i]}),
                                        content_type='application/json')
            return web.Response(text=json.dumps({'error': 'Not found'}),
                                content_type='application/json', status=404)

        async def delete(self, request, entry_id):
            import json
            from homeassistant.helpers.storage import Store
            store = Store(self.hass, _HISTORY_STORAGE_VERSION, _HISTORY_STORAGE_KEY)
            data = await store.async_load() or {"entries": []}
            before = len(data["entries"])
            data["entries"] = [e for e in data["entries"] if e["id"] != entry_id]
            if len(data["entries"]) == before:
                return web.Response(text=json.dumps({'error': 'Not found'}),
                                    content_type='application/json', status=404)
            await store.async_save(data)
            return web.Response(text=json.dumps({"ok": True}), content_type='application/json')

    class DiagnosticExportView(HomeAssistantView):
        """Export all calculation inputs and outputs as a zip for bug reporting."""

        url = "/api/grid_lens/diagnostic_export"
        name = "api:grid_lens:diagnostic_export"
        requires_auth = False

        def __init__(self, hass_instance):
            self.hass = hass_instance

        async def get(self, request):
            import io, json, zipfile
            from datetime import datetime as _dt

            entries = self.hass.config_entries.async_entries(DOMAIN)
            coordinator = self.hass.data.get(DOMAIN, {}).get(entries[0].entry_id) if entries else None

            if not coordinator:
                return web.Response(
                    text=json.dumps({'error': 'Integration not loaded'}),
                    content_type='application/json',
                    status=404,
                )
            if not coordinator.data:
                return web.Response(
                    text=json.dumps({'status': 'no_data', 'message': 'No calculation yet. Load the dashboard first.'}),
                    content_type='application/json',
                    status=202,
                )

            data = coordinator.data
            entry = coordinator.entry

            try:
                from homeassistant.const import __version__ as ha_version
            except Exception:
                ha_version = 'unknown'

            buf = io.BytesIO()
            timestamp = _dt.now().strftime('%Y%m%d_%H%M%S')

            with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zf:
                zf.writestr('README.txt', _DIAGNOSTIC_README)

                # System info and sensor entity IDs
                info = {
                    'exported_at': _dt.now().isoformat(),
                    'ha_version': ha_version,
                    'integration_domain': DOMAIN,
                    'calculation_date': data.get('calculation_date', ''),
                    'period_start': data.get('start_date', ''),
                    'period_end': data.get('end_date', ''),
                    'usage_days': data.get('usage_days', 0),
                    'current_plan': data.get('current_plan_name', ''),
                    'sensors': {
                        'energy': entry.data.get('energy_sensor', ''),
                        'solar': entry.data.get('solar_sensor', ''),
                        'grid_export': entry.data.get('grid_export_sensor', ''),
                        'import_price': entry.data.get('import_price_sensor', ''),
                        'export_price': entry.data.get('export_price_sensor', ''),
                        'battery_soc': entry.data.get('battery_soc_sensor', ''),
                        'battery_power': entry.data.get('battery_charge_power_sensor', ''),
                    },
                }
                zf.writestr('info.json', json.dumps(info, indent=2, default=str))

                # Battery and deferrable load configuration
                config = {
                    'has_battery': entry.data.get('has_battery', False),
                    'battery_capacity_kwh': entry.data.get('battery_capacity', 13.5),
                    'battery_max_charge_kw': entry.data.get('battery_max_charge_rate', 5.0),
                    'battery_max_discharge_kw': entry.data.get('battery_max_discharge_rate', 5.0),
                    'battery_efficiency_pct': entry.data.get('battery_efficiency', 95.0),
                    'battery_min_soc_pct': entry.data.get('battery_min_soc', 10.0),
                    'battery_max_soc_pct': entry.data.get('battery_max_soc', 90.0),
                    'deferrable_load_sensors': entry.data.get('deferrable_load_sensors', []),
                    'deferrable_load_max_kw': entry.data.get('deferrable_load_max_kw', []),
                }
                zf.writestr('config.json', json.dumps(config, indent=2, default=str))

                # All plan rate structures (from cached coordinator data, if available)
                coordinator_data = self.hass.data.get(DOMAIN, {}).get(entry_obj.entry_id)
                if coordinator_data and hasattr(coordinator_data, 'data') and coordinator_data.data:
                    plan_rates = coordinator_data.data.get('plan_data', {})
                    zf.writestr('plan_rates.json', json.dumps(plan_rates, indent=2, default=str))

                # Per-plan costs and savings
                summary = {
                    'current_plan': data.get('current_plan_name'),
                    'current_plan_total_dollars': data.get('amber_total', 0),
                    'usage_days': data.get('usage_days', 0),
                    'period_start': data.get('start_date'),
                    'period_end': data.get('end_date'),
                    'plan_costs': data.get('alternative_plans', {}),
                    'savings_vs_current': {
                        k: v for k, v in data.items() if k.endswith('_vs_current')
                    },
                }
                zf.writestr('calculation_summary.json', json.dumps(summary, indent=2, default=str))

                # Energy flows (first 24h)
                zf.writestr('energy_flows.json', json.dumps(
                    data.get('energy_flows', {}), indent=2, default=str
                ))

                # Per-plan LP schedules, breakdowns, and hourly profiles
                for plan_key, detail in data.get('plan_details', {}).items():
                    safe_name = ''.join(
                        c if c.isalnum() or c in '-_' else '_' for c in plan_key
                    )
                    opt = detail.get('optimization') or {}
                    plan_export = {
                        'plan_key': plan_key,
                        'strategy': detail.get('strategy', ''),
                        'plan_info': detail.get('plan_info', {}),
                        'breakdown': detail.get('breakdown', {}),
                        'hourly_profile_24h': detail.get('hourly_profile', []),
                        'optimization_totals': {
                            k: v for k, v in opt.items()
                            if k not in ('schedule', 'day_profile')
                        },
                        'lp_schedule': opt.get('schedule', []),
                    }
                    zf.writestr(
                        f'plans/{safe_name}.json',
                        json.dumps(plan_export, indent=2, default=str),
                    )

            buf.seek(0)
            filename = f"epc_diagnostic_{timestamp}.zip"
            return web.Response(
                body=buf.read(),
                content_type='application/zip',
                headers={'Content-Disposition': f'attachment; filename="{filename}"'},
            )

    class PlanStreamView(HomeAssistantView):
        """Stream plan results one-by-one via Server-Sent Events as each LP finishes."""

        url = "/api/grid_lens/plan_stream"
        name = "api:grid_lens:plan_stream"
        requires_auth = False

        def __init__(self, hass_instance):
            self.hass = hass_instance

        async def get(self, request):
            import json
            from datetime import datetime
            try:
                from zoneinfo import ZoneInfo
            except ImportError:
                from backports.zoneinfo import ZoneInfo
            ha_tz = ZoneInfo(self.hass.config.time_zone or "UTC")

            def _parse_date(s):
                if not s:
                    return None
                dt = datetime.fromisoformat(s.replace('Z', '+00:00'))
                return dt.replace(tzinfo=ha_tz) if dt.tzinfo is None else dt

            start_date = _parse_date(request.query.get('start_date'))
            end_date   = _parse_date(request.query.get('end_date'))

            entries = self.hass.config_entries.async_entries(DOMAIN)
            if not entries:
                return web.Response(
                    text=json.dumps({'error': 'Integration not loaded'}),
                    content_type='application/json', status=404,
                )

            entry_obj = entries[0]

            # Set up SSE stream
            resp = web.StreamResponse(headers={
                'Content-Type': 'text/event-stream',
                'Cache-Control': 'no-cache',
                'X-Accel-Buffering': 'no',
                'Access-Control-Allow-Origin': '*',
            })
            await resp.prepare(request)

            async def send(event, data):
                try:
                    payload = f"event: {event}\ndata: {json.dumps(data, default=str)}\n\n"
                    await resp.write(payload.encode())
                except Exception:
                    pass  # client disconnected

            from .const import CONF_GRIDLENS_API_KEY, CONF_GRIDLENS_API_URL, CONF_STATE

            api_key = entry_obj.data.get(CONF_GRIDLENS_API_KEY, "")
            api_url = entry_obj.data.get(CONF_GRIDLENS_API_URL, "https://api.gridlens.au")
            state   = entry_obj.data.get(CONF_STATE, "NSW")

            # Fetch plan data from API — enforces tier (free → locked plan only).
            _LOGGER.info("Fetching plans from API (state=%s)", state)
            plan_data: dict = {}
            try:
                _session = async_get_clientsession(self.hass)
                async with _session.get(
                    f"{api_url}/plans",
                    params={"state": state},
                    headers={"X-API-Key": api_key, "User-Agent": "GridLens-HA-Integration/1.0"},
                    timeout=aiohttp.ClientTimeout(total=15),
                ) as _r:
                    if _r.status == 200:
                        _resp = await _r.json()
                        plan_data = _resp.get("plans", {})
                        _LOGGER.info("Loaded %d plan(s) from API (tier=%s)", len(plan_data), _resp.get("tier"))
                    else:
                        _body = await _r.text()
                        _LOGGER.warning("API /plans returned %s: %s", _r.status, _body[:200])
            except Exception as _exc:
                _LOGGER.warning("Could not fetch plan data from API: %s", _exc)

            plans_total = len(plan_data) or 1
            plans_done  = 0

            await send('status', {
                'phase': 'fetching',
                'message': 'Fetching energy data…',
                'plans_total': plans_total,
            })

            # Apply plan-history override if available
            from .plan_calculator import PlanCalculator
            calculator = PlanCalculator(self.hass, entry_obj)
            calculator.plan_data = plan_data

            if start_date:
                from homeassistant.helpers.storage import Store
                hist_store = Store(self.hass, _HISTORY_STORAGE_VERSION, _HISTORY_STORAGE_KEY)
                hist_data  = await hist_store.async_load() or {"entries": []}
                hist_plan  = _plan_from_history(hist_data["entries"], start_date)
                if hist_plan:
                    calculator.current_plan_override = hist_plan

            async def on_plan_ready(plan_key, detail, meta):
                nonlocal plans_done
                plans_done += 1
                await send('plan', {
                    'plan_key':          plan_key,
                    'detail':            detail,
                    'plans_done':        plans_done,
                    'plans_total':       plans_total,
                    'current_plan_name': meta.get('current_plan_name'),
                    'alternative_plans': meta.get('alternative_plans', {}),
                    'amber_total':       meta.get('amber_total', 0),
                    'usage_days':        meta.get('usage_days', 0),
                    'start_date':        meta.get('start_date', ''),
                    'end_date':          meta.get('end_date', ''),
                    'energy_flows':      meta.get('energy_flows', {}),
                    'deferrable_devices': meta.get('deferrable_devices', []),
                })

            result = await calculator.calculate_plan_costs(
                start_date, end_date, on_plan_ready=on_plan_ready
            )
            await send('complete', result)
            return resp

    class SubscribeCallbackView(HomeAssistantView):
        """Receive subscription callback from gridlens.au and advance the config flow."""

        url = "/api/grid_lens/subscribe_callback"
        name = "api:grid_lens:subscribe_callback"
        requires_auth = False  # browser redirect from external site; flow_id is the token

        def __init__(self, hass_instance):
            self.hass = hass_instance

        async def get(self, request):
            flow_id = request.query.get("flow_id")
            api_key = request.query.get("api_key", "")

            if not flow_id:
                return web.Response(text="Missing flow_id.", status=400)

            self.hass.data.setdefault(DOMAIN, {}).setdefault(
                "pending_subscriptions", {}
            )[flow_id] = api_key

            try:
                await self.hass.config_entries.flow.async_configure(flow_id, {})
            except Exception as err:
                _LOGGER.warning("Could not advance subscribe flow %s: %s", flow_id, err)

            html = """<!DOCTYPE html>
<html>
<head>
  <title>Grid Lens</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body{font-family:sans-serif;display:flex;align-items:center;justify-content:center;
         height:100vh;margin:0;background:#1c1c1e;color:#fff}
    .card{text-align:center;padding:2rem}
    h1{font-size:1.5rem;margin-bottom:.5rem}
    p{color:#aaa}
  </style>
</head>
<body>
  <div class="card">
    <h1>You\'re all set!</h1>
    <p>Return to Home Assistant to complete setup.</p>
  </div>
  <script>if(window.opener){window.close()}</script>
</body>
</html>"""
            return web.Response(text=html, content_type="text/html")

    hass.http.register_view(PlanDataView(hass))
    hass.http.register_view(PlanHistoryView(hass))
    hass.http.register_view(PlanHistoryItemView(hass))
    hass.http.register_view(DiagnosticExportView(hass))
    hass.http.register_view(PlanStreamView(hass))
    hass.http.register_view(SubscribeCallbackView(hass))

    return True


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up Grid Lens from a config entry."""
    _LOGGER.info("Setting up Grid Lens")

    hass.data.setdefault(DOMAIN, {})

    coordinator = GridLensCoordinator(hass, entry)
    hass.data[DOMAIN][entry.entry_id] = coordinator

    # Register services
    from .services import async_setup_services
    await async_setup_services(hass, entry)

    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

    # Pre-calculate in the background so the card has data immediately on load.
    hass.async_create_task(coordinator.async_refresh())

    return True


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Unload a config entry."""
    if unload_ok := await hass.config_entries.async_unload_platforms(entry, PLATFORMS):
        hass.data[DOMAIN].pop(entry.entry_id)
    
    return unload_ok


class GridLensCoordinator(DataUpdateCoordinator):
    """Coordinator to manage electricity plan comparison data."""

    def __init__(self, hass: HomeAssistant, entry: ConfigEntry) -> None:
        """Initialize coordinator."""
        super().__init__(
            hass,
            _LOGGER,
            name=DOMAIN,
            update_interval=None,  # Manual refresh only — never auto-calculate
        )
        self.entry = entry
        self.hass = hass
        self.calculator = None  # Will be created on first update

    async def _async_update_data(self):
        """Fetch data from energy sensors and calculate plan comparisons."""
        import aiohttp
        from .plan_calculator import PlanCalculator
        from .const import CONF_GRIDLENS_API_KEY, CONF_GRIDLENS_API_URL, CONF_STATE

        api_key = self.entry.data.get(CONF_GRIDLENS_API_KEY, "")
        api_url = self.entry.data.get(CONF_GRIDLENS_API_URL, "https://api.gridlens.au")
        state   = self.entry.data.get(CONF_STATE, "NSW")

        plan_data: dict = {}
        try:
            import aiohttp as _aiohttp
            _session = async_get_clientsession(self.hass)
            async with _session.get(
                f"{api_url}/plans",
                params={"state": state},
                headers={"X-API-Key": api_key},
                timeout=_aiohttp.ClientTimeout(total=15),
            ) as _r:
                if _r.status == 200:
                    _resp = await _r.json()
                    plan_data = _resp.get("plans", {})
                else:
                    _LOGGER.warning("Coordinator: API /plans returned %s", _r.status)
        except Exception as _exc:
            _LOGGER.warning("Coordinator: could not fetch plan data: %s", _exc)

        self.calculator = PlanCalculator(self.hass, self.entry)
        self.calculator.plan_data = plan_data
        result = await self.calculator.calculate_plan_costs()
        _LOGGER.info(f"Plan calculation complete: {result.get('usage_days', 0)} days")

        # Build per-plan sensor data for CoordinatorEntity sensors
        plan_metrics = {}
        plan_details = result.get("plan_details", {})
        for plan_id, plan_key in PLAN_ID_TO_KEY.items():
            detail = plan_details.get(plan_key, {})
            opt = detail.get("optimization", {})
            schedule = opt.get("schedule", [])

            total_import = opt.get("total_import_kwh", 0.0) or 0.0
            total_export = opt.get("total_export_kwh", 0.0) or 0.0
            total_import_cost = opt.get("total_import_cost", 0.0) or 0.0
            total_export_credit = opt.get("total_export_credit", 0.0) or 0.0
            total_charge = sum(h.get("charge_kwh", 0) for h in schedule)
            total_discharge = sum(h.get("discharge_kwh", 0) for h in schedule)
            net_cost = opt.get("net_cost", detail.get("breakdown", {}).get("total", 0.0)) or 0.0

            plan_metrics[plan_id] = {
                "grid_import": round(total_import, 3),
                "grid_export": round(total_export, 3),
                "battery_charge": round(total_charge, 3),
                "battery_discharge": round(total_discharge, 3),
                "solar_production": 0.0,
                "buy_price": round(total_import_cost / total_import, 4) if total_import else 0.0,
                "sell_price": round(total_export_credit / total_export, 4) if total_export else 0.0,
                "hourly_cost": round(net_cost / len(schedule), 4) if schedule else 0.0,
                "optimization_notes": detail.get("strategy", ""),
            }

        result["plan_metrics"] = plan_metrics
        return result
